// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: io/casperlabs/ipc/transforms/transforms.proto

package transforms

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	state "github.com/hdac-io/casperlabs-ee-grpc-go-util/protobuf/io/casperlabs/casper/consensus/state"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type TypeMismatch struct {
	Expected             string   `protobuf:"bytes,1,opt,name=expected,proto3" json:"expected,omitempty"`
	Found                string   `protobuf:"bytes,2,opt,name=found,proto3" json:"found,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TypeMismatch) Reset()         { *m = TypeMismatch{} }
func (m *TypeMismatch) String() string { return proto.CompactTextString(m) }
func (*TypeMismatch) ProtoMessage()    {}
func (*TypeMismatch) Descriptor() ([]byte, []int) {
	return fileDescriptor_5e44d0312ff5f8ea, []int{0}
}
func (m *TypeMismatch) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TypeMismatch.Unmarshal(m, b)
}
func (m *TypeMismatch) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TypeMismatch.Marshal(b, m, deterministic)
}
func (m *TypeMismatch) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TypeMismatch.Merge(m, src)
}
func (m *TypeMismatch) XXX_Size() int {
	return xxx_messageInfo_TypeMismatch.Size(m)
}
func (m *TypeMismatch) XXX_DiscardUnknown() {
	xxx_messageInfo_TypeMismatch.DiscardUnknown(m)
}

var xxx_messageInfo_TypeMismatch proto.InternalMessageInfo

func (m *TypeMismatch) GetExpected() string {
	if m != nil {
		return m.Expected
	}
	return ""
}

func (m *TypeMismatch) GetFound() string {
	if m != nil {
		return m.Found
	}
	return ""
}

// Final transformation to the value under the key.
// It's the outcome of applying all `op`s
type Transform struct {
	// Types that are valid to be assigned to TransformInstance:
	//	*Transform_Identity
	//	*Transform_AddI32
	//	*Transform_AddU64
	//	*Transform_Write
	//	*Transform_AddKeys
	//	*Transform_Failure
	//	*Transform_AddBigInt
	TransformInstance    isTransform_TransformInstance `protobuf_oneof:"transform_instance"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *Transform) Reset()         { *m = Transform{} }
func (m *Transform) String() string { return proto.CompactTextString(m) }
func (*Transform) ProtoMessage()    {}
func (*Transform) Descriptor() ([]byte, []int) {
	return fileDescriptor_5e44d0312ff5f8ea, []int{1}
}
func (m *Transform) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transform.Unmarshal(m, b)
}
func (m *Transform) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transform.Marshal(b, m, deterministic)
}
func (m *Transform) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transform.Merge(m, src)
}
func (m *Transform) XXX_Size() int {
	return xxx_messageInfo_Transform.Size(m)
}
func (m *Transform) XXX_DiscardUnknown() {
	xxx_messageInfo_Transform.DiscardUnknown(m)
}

var xxx_messageInfo_Transform proto.InternalMessageInfo

type isTransform_TransformInstance interface {
	isTransform_TransformInstance()
}

type Transform_Identity struct {
	Identity *TransformIdentity `protobuf:"bytes,1,opt,name=identity,proto3,oneof" json:"identity,omitempty"`
}
type Transform_AddI32 struct {
	AddI32 *TransformAddInt32 `protobuf:"bytes,2,opt,name=add_i32,json=addI32,proto3,oneof" json:"add_i32,omitempty"`
}
type Transform_AddU64 struct {
	AddU64 *TransformAddUInt64 `protobuf:"bytes,3,opt,name=add_u64,json=addU64,proto3,oneof" json:"add_u64,omitempty"`
}
type Transform_Write struct {
	Write *TransformWrite `protobuf:"bytes,4,opt,name=write,proto3,oneof" json:"write,omitempty"`
}
type Transform_AddKeys struct {
	AddKeys *TransformAddKeys `protobuf:"bytes,5,opt,name=add_keys,json=addKeys,proto3,oneof" json:"add_keys,omitempty"`
}
type Transform_Failure struct {
	Failure *TransformFailure `protobuf:"bytes,6,opt,name=failure,proto3,oneof" json:"failure,omitempty"`
}
type Transform_AddBigInt struct {
	AddBigInt *TransformAddBigInt `protobuf:"bytes,7,opt,name=add_big_int,json=addBigInt,proto3,oneof" json:"add_big_int,omitempty"`
}

func (*Transform_Identity) isTransform_TransformInstance()  {}
func (*Transform_AddI32) isTransform_TransformInstance()    {}
func (*Transform_AddU64) isTransform_TransformInstance()    {}
func (*Transform_Write) isTransform_TransformInstance()     {}
func (*Transform_AddKeys) isTransform_TransformInstance()   {}
func (*Transform_Failure) isTransform_TransformInstance()   {}
func (*Transform_AddBigInt) isTransform_TransformInstance() {}

func (m *Transform) GetTransformInstance() isTransform_TransformInstance {
	if m != nil {
		return m.TransformInstance
	}
	return nil
}

func (m *Transform) GetIdentity() *TransformIdentity {
	if x, ok := m.GetTransformInstance().(*Transform_Identity); ok {
		return x.Identity
	}
	return nil
}

func (m *Transform) GetAddI32() *TransformAddInt32 {
	if x, ok := m.GetTransformInstance().(*Transform_AddI32); ok {
		return x.AddI32
	}
	return nil
}

func (m *Transform) GetAddU64() *TransformAddUInt64 {
	if x, ok := m.GetTransformInstance().(*Transform_AddU64); ok {
		return x.AddU64
	}
	return nil
}

func (m *Transform) GetWrite() *TransformWrite {
	if x, ok := m.GetTransformInstance().(*Transform_Write); ok {
		return x.Write
	}
	return nil
}

func (m *Transform) GetAddKeys() *TransformAddKeys {
	if x, ok := m.GetTransformInstance().(*Transform_AddKeys); ok {
		return x.AddKeys
	}
	return nil
}

func (m *Transform) GetFailure() *TransformFailure {
	if x, ok := m.GetTransformInstance().(*Transform_Failure); ok {
		return x.Failure
	}
	return nil
}

func (m *Transform) GetAddBigInt() *TransformAddBigInt {
	if x, ok := m.GetTransformInstance().(*Transform_AddBigInt); ok {
		return x.AddBigInt
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Transform) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Transform_Identity)(nil),
		(*Transform_AddI32)(nil),
		(*Transform_AddU64)(nil),
		(*Transform_Write)(nil),
		(*Transform_AddKeys)(nil),
		(*Transform_Failure)(nil),
		(*Transform_AddBigInt)(nil),
	}
}

type TransformIdentity struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TransformIdentity) Reset()         { *m = TransformIdentity{} }
func (m *TransformIdentity) String() string { return proto.CompactTextString(m) }
func (*TransformIdentity) ProtoMessage()    {}
func (*TransformIdentity) Descriptor() ([]byte, []int) {
	return fileDescriptor_5e44d0312ff5f8ea, []int{2}
}
func (m *TransformIdentity) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransformIdentity.Unmarshal(m, b)
}
func (m *TransformIdentity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransformIdentity.Marshal(b, m, deterministic)
}
func (m *TransformIdentity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransformIdentity.Merge(m, src)
}
func (m *TransformIdentity) XXX_Size() int {
	return xxx_messageInfo_TransformIdentity.Size(m)
}
func (m *TransformIdentity) XXX_DiscardUnknown() {
	xxx_messageInfo_TransformIdentity.DiscardUnknown(m)
}

var xxx_messageInfo_TransformIdentity proto.InternalMessageInfo

type TransformAddInt32 struct {
	Value                int32    `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TransformAddInt32) Reset()         { *m = TransformAddInt32{} }
func (m *TransformAddInt32) String() string { return proto.CompactTextString(m) }
func (*TransformAddInt32) ProtoMessage()    {}
func (*TransformAddInt32) Descriptor() ([]byte, []int) {
	return fileDescriptor_5e44d0312ff5f8ea, []int{3}
}
func (m *TransformAddInt32) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransformAddInt32.Unmarshal(m, b)
}
func (m *TransformAddInt32) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransformAddInt32.Marshal(b, m, deterministic)
}
func (m *TransformAddInt32) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransformAddInt32.Merge(m, src)
}
func (m *TransformAddInt32) XXX_Size() int {
	return xxx_messageInfo_TransformAddInt32.Size(m)
}
func (m *TransformAddInt32) XXX_DiscardUnknown() {
	xxx_messageInfo_TransformAddInt32.DiscardUnknown(m)
}

var xxx_messageInfo_TransformAddInt32 proto.InternalMessageInfo

func (m *TransformAddInt32) GetValue() int32 {
	if m != nil {
		return m.Value
	}
	return 0
}

type TransformAddUInt64 struct {
	Value                uint64   `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TransformAddUInt64) Reset()         { *m = TransformAddUInt64{} }
func (m *TransformAddUInt64) String() string { return proto.CompactTextString(m) }
func (*TransformAddUInt64) ProtoMessage()    {}
func (*TransformAddUInt64) Descriptor() ([]byte, []int) {
	return fileDescriptor_5e44d0312ff5f8ea, []int{4}
}
func (m *TransformAddUInt64) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransformAddUInt64.Unmarshal(m, b)
}
func (m *TransformAddUInt64) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransformAddUInt64.Marshal(b, m, deterministic)
}
func (m *TransformAddUInt64) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransformAddUInt64.Merge(m, src)
}
func (m *TransformAddUInt64) XXX_Size() int {
	return xxx_messageInfo_TransformAddUInt64.Size(m)
}
func (m *TransformAddUInt64) XXX_DiscardUnknown() {
	xxx_messageInfo_TransformAddUInt64.DiscardUnknown(m)
}

var xxx_messageInfo_TransformAddUInt64 proto.InternalMessageInfo

func (m *TransformAddUInt64) GetValue() uint64 {
	if m != nil {
		return m.Value
	}
	return 0
}

type TransformAddBigInt struct {
	Value                *state.BigInt `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *TransformAddBigInt) Reset()         { *m = TransformAddBigInt{} }
func (m *TransformAddBigInt) String() string { return proto.CompactTextString(m) }
func (*TransformAddBigInt) ProtoMessage()    {}
func (*TransformAddBigInt) Descriptor() ([]byte, []int) {
	return fileDescriptor_5e44d0312ff5f8ea, []int{5}
}
func (m *TransformAddBigInt) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransformAddBigInt.Unmarshal(m, b)
}
func (m *TransformAddBigInt) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransformAddBigInt.Marshal(b, m, deterministic)
}
func (m *TransformAddBigInt) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransformAddBigInt.Merge(m, src)
}
func (m *TransformAddBigInt) XXX_Size() int {
	return xxx_messageInfo_TransformAddBigInt.Size(m)
}
func (m *TransformAddBigInt) XXX_DiscardUnknown() {
	xxx_messageInfo_TransformAddBigInt.DiscardUnknown(m)
}

var xxx_messageInfo_TransformAddBigInt proto.InternalMessageInfo

func (m *TransformAddBigInt) GetValue() *state.BigInt {
	if m != nil {
		return m.Value
	}
	return nil
}

type TransformAddKeys struct {
	Value                []*state.NamedKey `protobuf:"bytes,1,rep,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *TransformAddKeys) Reset()         { *m = TransformAddKeys{} }
func (m *TransformAddKeys) String() string { return proto.CompactTextString(m) }
func (*TransformAddKeys) ProtoMessage()    {}
func (*TransformAddKeys) Descriptor() ([]byte, []int) {
	return fileDescriptor_5e44d0312ff5f8ea, []int{6}
}
func (m *TransformAddKeys) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransformAddKeys.Unmarshal(m, b)
}
func (m *TransformAddKeys) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransformAddKeys.Marshal(b, m, deterministic)
}
func (m *TransformAddKeys) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransformAddKeys.Merge(m, src)
}
func (m *TransformAddKeys) XXX_Size() int {
	return xxx_messageInfo_TransformAddKeys.Size(m)
}
func (m *TransformAddKeys) XXX_DiscardUnknown() {
	xxx_messageInfo_TransformAddKeys.DiscardUnknown(m)
}

var xxx_messageInfo_TransformAddKeys proto.InternalMessageInfo

func (m *TransformAddKeys) GetValue() []*state.NamedKey {
	if m != nil {
		return m.Value
	}
	return nil
}

type TransformWrite struct {
	Value                *state.Value `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *TransformWrite) Reset()         { *m = TransformWrite{} }
func (m *TransformWrite) String() string { return proto.CompactTextString(m) }
func (*TransformWrite) ProtoMessage()    {}
func (*TransformWrite) Descriptor() ([]byte, []int) {
	return fileDescriptor_5e44d0312ff5f8ea, []int{7}
}
func (m *TransformWrite) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransformWrite.Unmarshal(m, b)
}
func (m *TransformWrite) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransformWrite.Marshal(b, m, deterministic)
}
func (m *TransformWrite) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransformWrite.Merge(m, src)
}
func (m *TransformWrite) XXX_Size() int {
	return xxx_messageInfo_TransformWrite.Size(m)
}
func (m *TransformWrite) XXX_DiscardUnknown() {
	xxx_messageInfo_TransformWrite.DiscardUnknown(m)
}

var xxx_messageInfo_TransformWrite proto.InternalMessageInfo

func (m *TransformWrite) GetValue() *state.Value {
	if m != nil {
		return m.Value
	}
	return nil
}

type TransformFailure struct {
	// Types that are valid to be assigned to FailureInstance:
	//	*TransformFailure_TypeMismatch
	FailureInstance      isTransformFailure_FailureInstance `protobuf_oneof:"failure_instance"`
	XXX_NoUnkeyedLiteral struct{}                           `json:"-"`
	XXX_unrecognized     []byte                             `json:"-"`
	XXX_sizecache        int32                              `json:"-"`
}

func (m *TransformFailure) Reset()         { *m = TransformFailure{} }
func (m *TransformFailure) String() string { return proto.CompactTextString(m) }
func (*TransformFailure) ProtoMessage()    {}
func (*TransformFailure) Descriptor() ([]byte, []int) {
	return fileDescriptor_5e44d0312ff5f8ea, []int{8}
}
func (m *TransformFailure) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransformFailure.Unmarshal(m, b)
}
func (m *TransformFailure) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransformFailure.Marshal(b, m, deterministic)
}
func (m *TransformFailure) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransformFailure.Merge(m, src)
}
func (m *TransformFailure) XXX_Size() int {
	return xxx_messageInfo_TransformFailure.Size(m)
}
func (m *TransformFailure) XXX_DiscardUnknown() {
	xxx_messageInfo_TransformFailure.DiscardUnknown(m)
}

var xxx_messageInfo_TransformFailure proto.InternalMessageInfo

type isTransformFailure_FailureInstance interface {
	isTransformFailure_FailureInstance()
}

type TransformFailure_TypeMismatch struct {
	TypeMismatch *TypeMismatch `protobuf:"bytes,1,opt,name=type_mismatch,json=typeMismatch,proto3,oneof" json:"type_mismatch,omitempty"`
}

func (*TransformFailure_TypeMismatch) isTransformFailure_FailureInstance() {}

func (m *TransformFailure) GetFailureInstance() isTransformFailure_FailureInstance {
	if m != nil {
		return m.FailureInstance
	}
	return nil
}

func (m *TransformFailure) GetTypeMismatch() *TypeMismatch {
	if x, ok := m.GetFailureInstance().(*TransformFailure_TypeMismatch); ok {
		return x.TypeMismatch
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*TransformFailure) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*TransformFailure_TypeMismatch)(nil),
	}
}

type TransformEntry struct {
	Key                  *state.Key `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Transform            *Transform `protobuf:"bytes,2,opt,name=transform,proto3" json:"transform,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *TransformEntry) Reset()         { *m = TransformEntry{} }
func (m *TransformEntry) String() string { return proto.CompactTextString(m) }
func (*TransformEntry) ProtoMessage()    {}
func (*TransformEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_5e44d0312ff5f8ea, []int{9}
}
func (m *TransformEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransformEntry.Unmarshal(m, b)
}
func (m *TransformEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransformEntry.Marshal(b, m, deterministic)
}
func (m *TransformEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransformEntry.Merge(m, src)
}
func (m *TransformEntry) XXX_Size() int {
	return xxx_messageInfo_TransformEntry.Size(m)
}
func (m *TransformEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_TransformEntry.DiscardUnknown(m)
}

var xxx_messageInfo_TransformEntry proto.InternalMessageInfo

func (m *TransformEntry) GetKey() *state.Key {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *TransformEntry) GetTransform() *Transform {
	if m != nil {
		return m.Transform
	}
	return nil
}

func init() {
	proto.RegisterType((*TypeMismatch)(nil), "io.casperlabs.ipc.transforms.TypeMismatch")
	proto.RegisterType((*Transform)(nil), "io.casperlabs.ipc.transforms.Transform")
	proto.RegisterType((*TransformIdentity)(nil), "io.casperlabs.ipc.transforms.TransformIdentity")
	proto.RegisterType((*TransformAddInt32)(nil), "io.casperlabs.ipc.transforms.TransformAddInt32")
	proto.RegisterType((*TransformAddUInt64)(nil), "io.casperlabs.ipc.transforms.TransformAddUInt64")
	proto.RegisterType((*TransformAddBigInt)(nil), "io.casperlabs.ipc.transforms.TransformAddBigInt")
	proto.RegisterType((*TransformAddKeys)(nil), "io.casperlabs.ipc.transforms.TransformAddKeys")
	proto.RegisterType((*TransformWrite)(nil), "io.casperlabs.ipc.transforms.TransformWrite")
	proto.RegisterType((*TransformFailure)(nil), "io.casperlabs.ipc.transforms.TransformFailure")
	proto.RegisterType((*TransformEntry)(nil), "io.casperlabs.ipc.transforms.TransformEntry")
}

func init() {
	proto.RegisterFile("io/casperlabs/ipc/transforms/transforms.proto", fileDescriptor_5e44d0312ff5f8ea)
}

var fileDescriptor_5e44d0312ff5f8ea = []byte{
	// 571 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x94, 0xdf, 0x6e, 0xd3, 0x30,
	0x14, 0xc6, 0x33, 0xfa, 0x67, 0xad, 0x37, 0xd0, 0x30, 0xbb, 0x88, 0x26, 0x2e, 0x50, 0x6f, 0x60,
	0x83, 0x26, 0x53, 0x5b, 0xf5, 0x86, 0x1b, 0x56, 0x31, 0x94, 0x52, 0x0d, 0x09, 0x6f, 0x05, 0xc4,
	0x4d, 0xe5, 0xda, 0x6e, 0x6b, 0xad, 0x75, 0xa2, 0xd8, 0x01, 0xf2, 0x1e, 0x3c, 0x0e, 0x0f, 0x87,
	0x1c, 0x27, 0x69, 0x42, 0x61, 0x64, 0x37, 0xd5, 0x39, 0xed, 0xf9, 0x7e, 0xfd, 0xec, 0x73, 0x7c,
	0x40, 0x97, 0xfb, 0x2e, 0xc1, 0x32, 0x60, 0xe1, 0x1a, 0xcf, 0xa5, 0xcb, 0x03, 0xe2, 0xaa, 0x10,
	0x0b, 0xb9, 0xf0, 0xc3, 0x8d, 0x2c, 0x84, 0x4e, 0x10, 0xfa, 0xca, 0x87, 0x4f, 0xb9, 0xef, 0x6c,
	0xcb, 0x1d, 0x1e, 0x10, 0x67, 0x5b, 0x73, 0x72, 0x5e, 0x86, 0x99, 0xd0, 0x25, 0xbe, 0x90, 0x4c,
	0xc8, 0x48, 0xba, 0x52, 0x61, 0xc5, 0xcc, 0xa7, 0xe1, 0x75, 0xde, 0x80, 0xc3, 0x9b, 0x38, 0x60,
	0x57, 0x5c, 0x6e, 0xb0, 0x22, 0x2b, 0x78, 0x02, 0x5a, 0xec, 0x47, 0xc0, 0x88, 0x62, 0xd4, 0xde,
	0x7b, 0xb6, 0xf7, 0xa2, 0x8d, 0xf2, 0x1c, 0x1e, 0x83, 0xc6, 0xc2, 0x8f, 0x04, 0xb5, 0x1f, 0x24,
	0x3f, 0x98, 0xa4, 0xf3, 0xab, 0x0e, 0xda, 0x37, 0x99, 0x05, 0x78, 0x05, 0x5a, 0x9c, 0x32, 0xa1,
	0xb8, 0x8a, 0x13, 0xfd, 0x41, 0xcf, 0x75, 0xee, 0xb2, 0xec, 0xe4, 0xd2, 0x71, 0x2a, 0xf3, 0x2c,
	0x94, 0x23, 0xe0, 0x7b, 0xb0, 0x8f, 0x29, 0x9d, 0xf1, 0x7e, 0x2f, 0xf9, 0xd3, 0xea, 0xb4, 0x0b,
	0x4a, 0xc7, 0x42, 0xf5, 0x7b, 0x9e, 0x85, 0x9a, 0x98, 0xd2, 0x71, 0xbf, 0x07, 0x27, 0x86, 0x15,
	0x0d, 0x07, 0x76, 0x2d, 0x61, 0x9d, 0x57, 0x67, 0x4d, 0xc7, 0x42, 0x0d, 0x07, 0x29, 0x6c, 0x3a,
	0x1c, 0xc0, 0xb7, 0xa0, 0xf1, 0x3d, 0xe4, 0x8a, 0xd9, 0xf5, 0x04, 0xf5, 0xaa, 0x22, 0xea, 0xb3,
	0xd6, 0x78, 0x16, 0x32, 0x62, 0x38, 0x01, 0x2d, 0x6d, 0xe9, 0x96, 0xc5, 0xd2, 0x6e, 0x24, 0x20,
	0xa7, 0xba, 0xa7, 0x09, 0x8b, 0xa5, 0x67, 0x21, 0x7d, 0x28, 0x1d, 0xea, 0xbb, 0x5a, 0x60, 0xbe,
	0x8e, 0x42, 0x66, 0x37, 0xef, 0xc5, 0x7a, 0x67, 0x54, 0x9a, 0x95, 0x02, 0x20, 0x02, 0x07, 0xda,
	0xd8, 0x9c, 0x2f, 0x67, 0x5c, 0x28, 0x7b, 0xff, 0xbe, 0xf7, 0x35, 0xe2, 0xcb, 0xb1, 0x50, 0x9e,
	0x85, 0xda, 0x38, 0x4b, 0x46, 0xc7, 0x00, 0xe6, 0xd5, 0x33, 0x2e, 0xa4, 0xc2, 0x82, 0xb0, 0xce,
	0x13, 0xf0, 0x78, 0x67, 0x04, 0x3a, 0xa7, 0x85, 0x2f, 0xb3, 0x4e, 0xea, 0xf1, 0xfb, 0x86, 0xd7,
	0x11, 0x4b, 0xe6, 0xaa, 0x81, 0x4c, 0xd2, 0x39, 0x03, 0x70, 0xb7, 0x51, 0xe5, 0xda, 0x7a, 0x56,
	0xfb, 0xa5, 0x5c, 0x6b, 0x7c, 0xc1, 0x51, 0xb1, 0x76, 0xb7, 0x95, 0x26, 0x74, 0xf2, 0x47, 0xe4,
	0x98, 0xe7, 0x63, 0xc4, 0x5b, 0xf2, 0xd1, 0x9f, 0xad, 0xd1, 0x23, 0x92, 0x71, 0x6b, 0x7f, 0xe9,
	0xc6, 0x3f, 0xb8, 0x1f, 0xf0, 0x86, 0x69, 0x7d, 0x46, 0xbe, 0x06, 0x8f, 0xca, 0xd3, 0x03, 0x2f,
	0xca, 0x7e, 0x5f, 0x56, 0xe3, 0x7e, 0xd2, 0x92, 0x0c, 0x1a, 0x17, 0xec, 0xa6, 0xdd, 0x87, 0x1f,
	0xc1, 0x43, 0x15, 0x07, 0x6c, 0xb6, 0x49, 0x57, 0x41, 0x8a, 0x3f, 0xfb, 0x4f, 0xd3, 0x0b, 0xcb,
	0xc3, 0xb3, 0xd0, 0xa1, 0x2a, 0xe4, 0x23, 0x08, 0x8e, 0xd2, 0x81, 0xda, 0xf6, 0xfb, 0xe7, 0x5e,
	0xe1, 0x40, 0x97, 0x42, 0x85, 0x31, 0x7c, 0x0d, 0x6a, 0xb7, 0x2c, 0x5b, 0x17, 0xa7, 0xd5, 0x8e,
	0xa3, 0x6f, 0x48, 0xab, 0xe0, 0x25, 0x68, 0xe7, 0x76, 0xd2, 0x1d, 0xf1, 0xbc, 0xe2, 0x9c, 0xa2,
	0xad, 0x72, 0x34, 0xfd, 0x7a, 0xbd, 0xe4, 0x6a, 0x15, 0xcd, 0x1d, 0xe2, 0x6f, 0xdc, 0x15, 0xc5,
	0xa4, 0xbc, 0x98, 0xbb, 0x8c, 0x75, 0x97, 0x61, 0x40, 0xba, 0x4b, 0xbf, 0x1b, 0x29, 0xbe, 0x76,
	0x93, 0xf5, 0x39, 0x8f, 0x16, 0xee, 0x5d, 0xfb, 0x7b, 0xde, 0x4c, 0xca, 0xfa, 0xbf, 0x03, 0x00,
	0x00, 0xff, 0xff, 0x56, 0xed, 0xaa, 0x82, 0xe6, 0x05, 0x00, 0x00,
}
