// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: io/casperlabs/casper/consensus/state/state.proto

package state

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type CLType_Simple int32

const (
	CLType_BOOL   CLType_Simple = 0
	CLType_I32    CLType_Simple = 1
	CLType_I64    CLType_Simple = 2
	CLType_U8     CLType_Simple = 3
	CLType_U32    CLType_Simple = 4
	CLType_U64    CLType_Simple = 5
	CLType_U128   CLType_Simple = 6
	CLType_U256   CLType_Simple = 7
	CLType_U512   CLType_Simple = 8
	CLType_UNIT   CLType_Simple = 9
	CLType_STRING CLType_Simple = 10
	CLType_KEY    CLType_Simple = 11
	CLType_UREF   CLType_Simple = 12
)

var CLType_Simple_name = map[int32]string{
	0:  "BOOL",
	1:  "I32",
	2:  "I64",
	3:  "U8",
	4:  "U32",
	5:  "U64",
	6:  "U128",
	7:  "U256",
	8:  "U512",
	9:  "UNIT",
	10: "STRING",
	11: "KEY",
	12: "UREF",
}

var CLType_Simple_value = map[string]int32{
	"BOOL":   0,
	"I32":    1,
	"I64":    2,
	"U8":     3,
	"U32":    4,
	"U64":    5,
	"U128":   6,
	"U256":   7,
	"U512":   8,
	"UNIT":   9,
	"STRING": 10,
	"KEY":    11,
	"UREF":   12,
}

func (x CLType_Simple) String() string {
	return proto.EnumName(CLType_Simple_name, int32(x))
}

func (CLType_Simple) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_bc5c211b7c38b10a, []int{0, 0}
}

// NOTE: Numeric values correspond to values of the domain
// AccessRights struct. DO NOT CHANGE.
type Key_URef_AccessRights int32

const (
	Key_URef_UNKNOWN        Key_URef_AccessRights = 0
	Key_URef_READ           Key_URef_AccessRights = 1
	Key_URef_WRITE          Key_URef_AccessRights = 2
	Key_URef_ADD            Key_URef_AccessRights = 4
	Key_URef_READ_ADD       Key_URef_AccessRights = 5
	Key_URef_READ_WRITE     Key_URef_AccessRights = 3
	Key_URef_ADD_WRITE      Key_URef_AccessRights = 6
	Key_URef_READ_ADD_WRITE Key_URef_AccessRights = 7
)

var Key_URef_AccessRights_name = map[int32]string{
	0: "UNKNOWN",
	1: "READ",
	2: "WRITE",
	4: "ADD",
	5: "READ_ADD",
	3: "READ_WRITE",
	6: "ADD_WRITE",
	7: "READ_ADD_WRITE",
}

var Key_URef_AccessRights_value = map[string]int32{
	"UNKNOWN":        0,
	"READ":           1,
	"WRITE":          2,
	"ADD":            4,
	"READ_ADD":       5,
	"READ_WRITE":     3,
	"ADD_WRITE":      6,
	"READ_ADD_WRITE": 7,
}

func (x Key_URef_AccessRights) String() string {
	return proto.EnumName(Key_URef_AccessRights_name, int32(x))
}

func (Key_URef_AccessRights) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_bc5c211b7c38b10a, []int{7, 2, 0}
}

// Fundamental type of a user-facing value stored under a key in global state.
type CLType struct {
	// Types that are valid to be assigned to Variants:
	//	*CLType_SimpleType
	//	*CLType_OptionType
	//	*CLType_ListType
	//	*CLType_FixedListType
	//	*CLType_ResultType
	//	*CLType_MapType
	//	*CLType_Tuple1Type
	//	*CLType_Tuple2Type
	//	*CLType_Tuple3Type
	//	*CLType_AnyType
	Variants             isCLType_Variants `protobuf_oneof:"variants"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *CLType) Reset()         { *m = CLType{} }
func (m *CLType) String() string { return proto.CompactTextString(m) }
func (*CLType) ProtoMessage()    {}
func (*CLType) Descriptor() ([]byte, []int) {
	return fileDescriptor_bc5c211b7c38b10a, []int{0}
}
func (m *CLType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CLType.Unmarshal(m, b)
}
func (m *CLType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CLType.Marshal(b, m, deterministic)
}
func (m *CLType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CLType.Merge(m, src)
}
func (m *CLType) XXX_Size() int {
	return xxx_messageInfo_CLType.Size(m)
}
func (m *CLType) XXX_DiscardUnknown() {
	xxx_messageInfo_CLType.DiscardUnknown(m)
}

var xxx_messageInfo_CLType proto.InternalMessageInfo

type isCLType_Variants interface {
	isCLType_Variants()
}

type CLType_SimpleType struct {
	SimpleType CLType_Simple `protobuf:"varint,1,opt,name=simple_type,json=simpleType,proto3,enum=io.casperlabs.casper.consensus.state.CLType_Simple,oneof" json:"simple_type,omitempty"`
}
type CLType_OptionType struct {
	OptionType *CLType_Option `protobuf:"bytes,2,opt,name=option_type,json=optionType,proto3,oneof" json:"option_type,omitempty"`
}
type CLType_ListType struct {
	ListType *CLType_List `protobuf:"bytes,3,opt,name=list_type,json=listType,proto3,oneof" json:"list_type,omitempty"`
}
type CLType_FixedListType struct {
	FixedListType *CLType_FixedList `protobuf:"bytes,4,opt,name=fixed_list_type,json=fixedListType,proto3,oneof" json:"fixed_list_type,omitempty"`
}
type CLType_ResultType struct {
	ResultType *CLType_Result `protobuf:"bytes,5,opt,name=result_type,json=resultType,proto3,oneof" json:"result_type,omitempty"`
}
type CLType_MapType struct {
	MapType *CLType_Map `protobuf:"bytes,6,opt,name=map_type,json=mapType,proto3,oneof" json:"map_type,omitempty"`
}
type CLType_Tuple1Type struct {
	Tuple1Type *CLType_Tuple1 `protobuf:"bytes,7,opt,name=tuple1_type,json=tuple1Type,proto3,oneof" json:"tuple1_type,omitempty"`
}
type CLType_Tuple2Type struct {
	Tuple2Type *CLType_Tuple2 `protobuf:"bytes,8,opt,name=tuple2_type,json=tuple2Type,proto3,oneof" json:"tuple2_type,omitempty"`
}
type CLType_Tuple3Type struct {
	Tuple3Type *CLType_Tuple3 `protobuf:"bytes,9,opt,name=tuple3_type,json=tuple3Type,proto3,oneof" json:"tuple3_type,omitempty"`
}
type CLType_AnyType struct {
	AnyType *CLType_Any `protobuf:"bytes,10,opt,name=any_type,json=anyType,proto3,oneof" json:"any_type,omitempty"`
}

func (*CLType_SimpleType) isCLType_Variants()    {}
func (*CLType_OptionType) isCLType_Variants()    {}
func (*CLType_ListType) isCLType_Variants()      {}
func (*CLType_FixedListType) isCLType_Variants() {}
func (*CLType_ResultType) isCLType_Variants()    {}
func (*CLType_MapType) isCLType_Variants()       {}
func (*CLType_Tuple1Type) isCLType_Variants()    {}
func (*CLType_Tuple2Type) isCLType_Variants()    {}
func (*CLType_Tuple3Type) isCLType_Variants()    {}
func (*CLType_AnyType) isCLType_Variants()       {}

func (m *CLType) GetVariants() isCLType_Variants {
	if m != nil {
		return m.Variants
	}
	return nil
}

func (m *CLType) GetSimpleType() CLType_Simple {
	if x, ok := m.GetVariants().(*CLType_SimpleType); ok {
		return x.SimpleType
	}
	return CLType_BOOL
}

func (m *CLType) GetOptionType() *CLType_Option {
	if x, ok := m.GetVariants().(*CLType_OptionType); ok {
		return x.OptionType
	}
	return nil
}

func (m *CLType) GetListType() *CLType_List {
	if x, ok := m.GetVariants().(*CLType_ListType); ok {
		return x.ListType
	}
	return nil
}

func (m *CLType) GetFixedListType() *CLType_FixedList {
	if x, ok := m.GetVariants().(*CLType_FixedListType); ok {
		return x.FixedListType
	}
	return nil
}

func (m *CLType) GetResultType() *CLType_Result {
	if x, ok := m.GetVariants().(*CLType_ResultType); ok {
		return x.ResultType
	}
	return nil
}

func (m *CLType) GetMapType() *CLType_Map {
	if x, ok := m.GetVariants().(*CLType_MapType); ok {
		return x.MapType
	}
	return nil
}

func (m *CLType) GetTuple1Type() *CLType_Tuple1 {
	if x, ok := m.GetVariants().(*CLType_Tuple1Type); ok {
		return x.Tuple1Type
	}
	return nil
}

func (m *CLType) GetTuple2Type() *CLType_Tuple2 {
	if x, ok := m.GetVariants().(*CLType_Tuple2Type); ok {
		return x.Tuple2Type
	}
	return nil
}

func (m *CLType) GetTuple3Type() *CLType_Tuple3 {
	if x, ok := m.GetVariants().(*CLType_Tuple3Type); ok {
		return x.Tuple3Type
	}
	return nil
}

func (m *CLType) GetAnyType() *CLType_Any {
	if x, ok := m.GetVariants().(*CLType_AnyType); ok {
		return x.AnyType
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*CLType) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*CLType_SimpleType)(nil),
		(*CLType_OptionType)(nil),
		(*CLType_ListType)(nil),
		(*CLType_FixedListType)(nil),
		(*CLType_ResultType)(nil),
		(*CLType_MapType)(nil),
		(*CLType_Tuple1Type)(nil),
		(*CLType_Tuple2Type)(nil),
		(*CLType_Tuple3Type)(nil),
		(*CLType_AnyType)(nil),
	}
}

type CLType_Option struct {
	Inner                *CLType  `protobuf:"bytes,1,opt,name=inner,proto3" json:"inner,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CLType_Option) Reset()         { *m = CLType_Option{} }
func (m *CLType_Option) String() string { return proto.CompactTextString(m) }
func (*CLType_Option) ProtoMessage()    {}
func (*CLType_Option) Descriptor() ([]byte, []int) {
	return fileDescriptor_bc5c211b7c38b10a, []int{0, 0}
}
func (m *CLType_Option) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CLType_Option.Unmarshal(m, b)
}
func (m *CLType_Option) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CLType_Option.Marshal(b, m, deterministic)
}
func (m *CLType_Option) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CLType_Option.Merge(m, src)
}
func (m *CLType_Option) XXX_Size() int {
	return xxx_messageInfo_CLType_Option.Size(m)
}
func (m *CLType_Option) XXX_DiscardUnknown() {
	xxx_messageInfo_CLType_Option.DiscardUnknown(m)
}

var xxx_messageInfo_CLType_Option proto.InternalMessageInfo

func (m *CLType_Option) GetInner() *CLType {
	if m != nil {
		return m.Inner
	}
	return nil
}

type CLType_List struct {
	Inner                *CLType  `protobuf:"bytes,1,opt,name=inner,proto3" json:"inner,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CLType_List) Reset()         { *m = CLType_List{} }
func (m *CLType_List) String() string { return proto.CompactTextString(m) }
func (*CLType_List) ProtoMessage()    {}
func (*CLType_List) Descriptor() ([]byte, []int) {
	return fileDescriptor_bc5c211b7c38b10a, []int{0, 1}
}
func (m *CLType_List) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CLType_List.Unmarshal(m, b)
}
func (m *CLType_List) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CLType_List.Marshal(b, m, deterministic)
}
func (m *CLType_List) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CLType_List.Merge(m, src)
}
func (m *CLType_List) XXX_Size() int {
	return xxx_messageInfo_CLType_List.Size(m)
}
func (m *CLType_List) XXX_DiscardUnknown() {
	xxx_messageInfo_CLType_List.DiscardUnknown(m)
}

var xxx_messageInfo_CLType_List proto.InternalMessageInfo

func (m *CLType_List) GetInner() *CLType {
	if m != nil {
		return m.Inner
	}
	return nil
}

type CLType_FixedList struct {
	Inner                *CLType  `protobuf:"bytes,1,opt,name=inner,proto3" json:"inner,omitempty"`
	Len                  uint32   `protobuf:"varint,2,opt,name=len,proto3" json:"len,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CLType_FixedList) Reset()         { *m = CLType_FixedList{} }
func (m *CLType_FixedList) String() string { return proto.CompactTextString(m) }
func (*CLType_FixedList) ProtoMessage()    {}
func (*CLType_FixedList) Descriptor() ([]byte, []int) {
	return fileDescriptor_bc5c211b7c38b10a, []int{0, 2}
}
func (m *CLType_FixedList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CLType_FixedList.Unmarshal(m, b)
}
func (m *CLType_FixedList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CLType_FixedList.Marshal(b, m, deterministic)
}
func (m *CLType_FixedList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CLType_FixedList.Merge(m, src)
}
func (m *CLType_FixedList) XXX_Size() int {
	return xxx_messageInfo_CLType_FixedList.Size(m)
}
func (m *CLType_FixedList) XXX_DiscardUnknown() {
	xxx_messageInfo_CLType_FixedList.DiscardUnknown(m)
}

var xxx_messageInfo_CLType_FixedList proto.InternalMessageInfo

func (m *CLType_FixedList) GetInner() *CLType {
	if m != nil {
		return m.Inner
	}
	return nil
}

func (m *CLType_FixedList) GetLen() uint32 {
	if m != nil {
		return m.Len
	}
	return 0
}

type CLType_Result struct {
	Ok                   *CLType  `protobuf:"bytes,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Err                  *CLType  `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CLType_Result) Reset()         { *m = CLType_Result{} }
func (m *CLType_Result) String() string { return proto.CompactTextString(m) }
func (*CLType_Result) ProtoMessage()    {}
func (*CLType_Result) Descriptor() ([]byte, []int) {
	return fileDescriptor_bc5c211b7c38b10a, []int{0, 3}
}
func (m *CLType_Result) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CLType_Result.Unmarshal(m, b)
}
func (m *CLType_Result) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CLType_Result.Marshal(b, m, deterministic)
}
func (m *CLType_Result) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CLType_Result.Merge(m, src)
}
func (m *CLType_Result) XXX_Size() int {
	return xxx_messageInfo_CLType_Result.Size(m)
}
func (m *CLType_Result) XXX_DiscardUnknown() {
	xxx_messageInfo_CLType_Result.DiscardUnknown(m)
}

var xxx_messageInfo_CLType_Result proto.InternalMessageInfo

func (m *CLType_Result) GetOk() *CLType {
	if m != nil {
		return m.Ok
	}
	return nil
}

func (m *CLType_Result) GetErr() *CLType {
	if m != nil {
		return m.Err
	}
	return nil
}

type CLType_Map struct {
	Key                  *CLType  `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                *CLType  `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CLType_Map) Reset()         { *m = CLType_Map{} }
func (m *CLType_Map) String() string { return proto.CompactTextString(m) }
func (*CLType_Map) ProtoMessage()    {}
func (*CLType_Map) Descriptor() ([]byte, []int) {
	return fileDescriptor_bc5c211b7c38b10a, []int{0, 4}
}
func (m *CLType_Map) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CLType_Map.Unmarshal(m, b)
}
func (m *CLType_Map) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CLType_Map.Marshal(b, m, deterministic)
}
func (m *CLType_Map) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CLType_Map.Merge(m, src)
}
func (m *CLType_Map) XXX_Size() int {
	return xxx_messageInfo_CLType_Map.Size(m)
}
func (m *CLType_Map) XXX_DiscardUnknown() {
	xxx_messageInfo_CLType_Map.DiscardUnknown(m)
}

var xxx_messageInfo_CLType_Map proto.InternalMessageInfo

func (m *CLType_Map) GetKey() *CLType {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *CLType_Map) GetValue() *CLType {
	if m != nil {
		return m.Value
	}
	return nil
}

type CLType_Tuple1 struct {
	Type0                *CLType  `protobuf:"bytes,1,opt,name=type0,proto3" json:"type0,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CLType_Tuple1) Reset()         { *m = CLType_Tuple1{} }
func (m *CLType_Tuple1) String() string { return proto.CompactTextString(m) }
func (*CLType_Tuple1) ProtoMessage()    {}
func (*CLType_Tuple1) Descriptor() ([]byte, []int) {
	return fileDescriptor_bc5c211b7c38b10a, []int{0, 5}
}
func (m *CLType_Tuple1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CLType_Tuple1.Unmarshal(m, b)
}
func (m *CLType_Tuple1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CLType_Tuple1.Marshal(b, m, deterministic)
}
func (m *CLType_Tuple1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CLType_Tuple1.Merge(m, src)
}
func (m *CLType_Tuple1) XXX_Size() int {
	return xxx_messageInfo_CLType_Tuple1.Size(m)
}
func (m *CLType_Tuple1) XXX_DiscardUnknown() {
	xxx_messageInfo_CLType_Tuple1.DiscardUnknown(m)
}

var xxx_messageInfo_CLType_Tuple1 proto.InternalMessageInfo

func (m *CLType_Tuple1) GetType0() *CLType {
	if m != nil {
		return m.Type0
	}
	return nil
}

type CLType_Tuple2 struct {
	Type0                *CLType  `protobuf:"bytes,1,opt,name=type0,proto3" json:"type0,omitempty"`
	Type1                *CLType  `protobuf:"bytes,2,opt,name=type1,proto3" json:"type1,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CLType_Tuple2) Reset()         { *m = CLType_Tuple2{} }
func (m *CLType_Tuple2) String() string { return proto.CompactTextString(m) }
func (*CLType_Tuple2) ProtoMessage()    {}
func (*CLType_Tuple2) Descriptor() ([]byte, []int) {
	return fileDescriptor_bc5c211b7c38b10a, []int{0, 6}
}
func (m *CLType_Tuple2) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CLType_Tuple2.Unmarshal(m, b)
}
func (m *CLType_Tuple2) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CLType_Tuple2.Marshal(b, m, deterministic)
}
func (m *CLType_Tuple2) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CLType_Tuple2.Merge(m, src)
}
func (m *CLType_Tuple2) XXX_Size() int {
	return xxx_messageInfo_CLType_Tuple2.Size(m)
}
func (m *CLType_Tuple2) XXX_DiscardUnknown() {
	xxx_messageInfo_CLType_Tuple2.DiscardUnknown(m)
}

var xxx_messageInfo_CLType_Tuple2 proto.InternalMessageInfo

func (m *CLType_Tuple2) GetType0() *CLType {
	if m != nil {
		return m.Type0
	}
	return nil
}

func (m *CLType_Tuple2) GetType1() *CLType {
	if m != nil {
		return m.Type1
	}
	return nil
}

type CLType_Tuple3 struct {
	Type0                *CLType  `protobuf:"bytes,1,opt,name=type0,proto3" json:"type0,omitempty"`
	Type1                *CLType  `protobuf:"bytes,2,opt,name=type1,proto3" json:"type1,omitempty"`
	Type2                *CLType  `protobuf:"bytes,3,opt,name=type2,proto3" json:"type2,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CLType_Tuple3) Reset()         { *m = CLType_Tuple3{} }
func (m *CLType_Tuple3) String() string { return proto.CompactTextString(m) }
func (*CLType_Tuple3) ProtoMessage()    {}
func (*CLType_Tuple3) Descriptor() ([]byte, []int) {
	return fileDescriptor_bc5c211b7c38b10a, []int{0, 7}
}
func (m *CLType_Tuple3) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CLType_Tuple3.Unmarshal(m, b)
}
func (m *CLType_Tuple3) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CLType_Tuple3.Marshal(b, m, deterministic)
}
func (m *CLType_Tuple3) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CLType_Tuple3.Merge(m, src)
}
func (m *CLType_Tuple3) XXX_Size() int {
	return xxx_messageInfo_CLType_Tuple3.Size(m)
}
func (m *CLType_Tuple3) XXX_DiscardUnknown() {
	xxx_messageInfo_CLType_Tuple3.DiscardUnknown(m)
}

var xxx_messageInfo_CLType_Tuple3 proto.InternalMessageInfo

func (m *CLType_Tuple3) GetType0() *CLType {
	if m != nil {
		return m.Type0
	}
	return nil
}

func (m *CLType_Tuple3) GetType1() *CLType {
	if m != nil {
		return m.Type1
	}
	return nil
}

func (m *CLType_Tuple3) GetType2() *CLType {
	if m != nil {
		return m.Type2
	}
	return nil
}

type CLType_Any struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CLType_Any) Reset()         { *m = CLType_Any{} }
func (m *CLType_Any) String() string { return proto.CompactTextString(m) }
func (*CLType_Any) ProtoMessage()    {}
func (*CLType_Any) Descriptor() ([]byte, []int) {
	return fileDescriptor_bc5c211b7c38b10a, []int{0, 8}
}
func (m *CLType_Any) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CLType_Any.Unmarshal(m, b)
}
func (m *CLType_Any) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CLType_Any.Marshal(b, m, deterministic)
}
func (m *CLType_Any) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CLType_Any.Merge(m, src)
}
func (m *CLType_Any) XXX_Size() int {
	return xxx_messageInfo_CLType_Any.Size(m)
}
func (m *CLType_Any) XXX_DiscardUnknown() {
	xxx_messageInfo_CLType_Any.DiscardUnknown(m)
}

var xxx_messageInfo_CLType_Any proto.InternalMessageInfo

// User-facing value stored under a key in global state.
type CLValue struct {
	ClType               *CLType  `protobuf:"bytes,1,opt,name=cl_type,json=clType,proto3" json:"cl_type,omitempty"`
	SerializedValue      []byte   `protobuf:"bytes,2,opt,name=serialized_value,json=serializedValue,proto3" json:"serialized_value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CLValue) Reset()         { *m = CLValue{} }
func (m *CLValue) String() string { return proto.CompactTextString(m) }
func (*CLValue) ProtoMessage()    {}
func (*CLValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_bc5c211b7c38b10a, []int{1}
}
func (m *CLValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CLValue.Unmarshal(m, b)
}
func (m *CLValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CLValue.Marshal(b, m, deterministic)
}
func (m *CLValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CLValue.Merge(m, src)
}
func (m *CLValue) XXX_Size() int {
	return xxx_messageInfo_CLValue.Size(m)
}
func (m *CLValue) XXX_DiscardUnknown() {
	xxx_messageInfo_CLValue.DiscardUnknown(m)
}

var xxx_messageInfo_CLValue proto.InternalMessageInfo

func (m *CLValue) GetClType() *CLType {
	if m != nil {
		return m.ClType
	}
	return nil
}

func (m *CLValue) GetSerializedValue() []byte {
	if m != nil {
		return m.SerializedValue
	}
	return nil
}

// Value stored under a key in global state.
type StoredValue struct {
	// Types that are valid to be assigned to Variants:
	//	*StoredValue_ClValue
	//	*StoredValue_Account
	//	*StoredValue_Contract
	Variants             isStoredValue_Variants `protobuf_oneof:"variants"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *StoredValue) Reset()         { *m = StoredValue{} }
func (m *StoredValue) String() string { return proto.CompactTextString(m) }
func (*StoredValue) ProtoMessage()    {}
func (*StoredValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_bc5c211b7c38b10a, []int{2}
}
func (m *StoredValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StoredValue.Unmarshal(m, b)
}
func (m *StoredValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StoredValue.Marshal(b, m, deterministic)
}
func (m *StoredValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StoredValue.Merge(m, src)
}
func (m *StoredValue) XXX_Size() int {
	return xxx_messageInfo_StoredValue.Size(m)
}
func (m *StoredValue) XXX_DiscardUnknown() {
	xxx_messageInfo_StoredValue.DiscardUnknown(m)
}

var xxx_messageInfo_StoredValue proto.InternalMessageInfo

type isStoredValue_Variants interface {
	isStoredValue_Variants()
}

type StoredValue_ClValue struct {
	ClValue *CLValue `protobuf:"bytes,1,opt,name=cl_value,json=clValue,proto3,oneof" json:"cl_value,omitempty"`
}
type StoredValue_Account struct {
	Account *Account `protobuf:"bytes,2,opt,name=account,proto3,oneof" json:"account,omitempty"`
}
type StoredValue_Contract struct {
	Contract *Contract `protobuf:"bytes,3,opt,name=contract,proto3,oneof" json:"contract,omitempty"`
}

func (*StoredValue_ClValue) isStoredValue_Variants()  {}
func (*StoredValue_Account) isStoredValue_Variants()  {}
func (*StoredValue_Contract) isStoredValue_Variants() {}

func (m *StoredValue) GetVariants() isStoredValue_Variants {
	if m != nil {
		return m.Variants
	}
	return nil
}

func (m *StoredValue) GetClValue() *CLValue {
	if x, ok := m.GetVariants().(*StoredValue_ClValue); ok {
		return x.ClValue
	}
	return nil
}

func (m *StoredValue) GetAccount() *Account {
	if x, ok := m.GetVariants().(*StoredValue_Account); ok {
		return x.Account
	}
	return nil
}

func (m *StoredValue) GetContract() *Contract {
	if x, ok := m.GetVariants().(*StoredValue_Contract); ok {
		return x.Contract
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*StoredValue) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*StoredValue_ClValue)(nil),
		(*StoredValue_Account)(nil),
		(*StoredValue_Contract)(nil),
	}
}

type Value struct {
	// Types that are valid to be assigned to Value:
	//	*Value_IntValue
	//	*Value_BytesValue
	//	*Value_IntList
	//	*Value_StringValue
	//	*Value_Account
	//	*Value_Contract
	//	*Value_StringList
	//	*Value_NamedKey
	//	*Value_BigInt
	//	*Value_Key
	//	*Value_Unit
	//	*Value_LongValue
	Value                isValue_Value `protobuf_oneof:"value"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Value) Reset()         { *m = Value{} }
func (m *Value) String() string { return proto.CompactTextString(m) }
func (*Value) ProtoMessage()    {}
func (*Value) Descriptor() ([]byte, []int) {
	return fileDescriptor_bc5c211b7c38b10a, []int{3}
}
func (m *Value) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Value.Unmarshal(m, b)
}
func (m *Value) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Value.Marshal(b, m, deterministic)
}
func (m *Value) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Value.Merge(m, src)
}
func (m *Value) XXX_Size() int {
	return xxx_messageInfo_Value.Size(m)
}
func (m *Value) XXX_DiscardUnknown() {
	xxx_messageInfo_Value.DiscardUnknown(m)
}

var xxx_messageInfo_Value proto.InternalMessageInfo

type isValue_Value interface {
	isValue_Value()
}

type Value_IntValue struct {
	IntValue int32 `protobuf:"varint,1,opt,name=int_value,json=intValue,proto3,oneof" json:"int_value,omitempty"`
}
type Value_BytesValue struct {
	BytesValue []byte `protobuf:"bytes,2,opt,name=bytes_value,json=bytesValue,proto3,oneof" json:"bytes_value,omitempty"`
}
type Value_IntList struct {
	IntList *IntList `protobuf:"bytes,3,opt,name=int_list,json=intList,proto3,oneof" json:"int_list,omitempty"`
}
type Value_StringValue struct {
	StringValue string `protobuf:"bytes,4,opt,name=string_value,json=stringValue,proto3,oneof" json:"string_value,omitempty"`
}
type Value_Account struct {
	Account *Account `protobuf:"bytes,5,opt,name=account,proto3,oneof" json:"account,omitempty"`
}
type Value_Contract struct {
	Contract *Contract `protobuf:"bytes,6,opt,name=contract,proto3,oneof" json:"contract,omitempty"`
}
type Value_StringList struct {
	StringList *StringList `protobuf:"bytes,7,opt,name=string_list,json=stringList,proto3,oneof" json:"string_list,omitempty"`
}
type Value_NamedKey struct {
	NamedKey *NamedKey `protobuf:"bytes,8,opt,name=named_key,json=namedKey,proto3,oneof" json:"named_key,omitempty"`
}
type Value_BigInt struct {
	BigInt *BigInt `protobuf:"bytes,9,opt,name=big_int,json=bigInt,proto3,oneof" json:"big_int,omitempty"`
}
type Value_Key struct {
	Key *Key `protobuf:"bytes,10,opt,name=key,proto3,oneof" json:"key,omitempty"`
}
type Value_Unit struct {
	Unit *Unit `protobuf:"bytes,11,opt,name=unit,proto3,oneof" json:"unit,omitempty"`
}
type Value_LongValue struct {
	LongValue uint64 `protobuf:"varint,12,opt,name=long_value,json=longValue,proto3,oneof" json:"long_value,omitempty"`
}

func (*Value_IntValue) isValue_Value()    {}
func (*Value_BytesValue) isValue_Value()  {}
func (*Value_IntList) isValue_Value()     {}
func (*Value_StringValue) isValue_Value() {}
func (*Value_Account) isValue_Value()     {}
func (*Value_Contract) isValue_Value()    {}
func (*Value_StringList) isValue_Value()  {}
func (*Value_NamedKey) isValue_Value()    {}
func (*Value_BigInt) isValue_Value()      {}
func (*Value_Key) isValue_Value()         {}
func (*Value_Unit) isValue_Value()        {}
func (*Value_LongValue) isValue_Value()   {}

func (m *Value) GetValue() isValue_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *Value) GetIntValue() int32 {
	if x, ok := m.GetValue().(*Value_IntValue); ok {
		return x.IntValue
	}
	return 0
}

func (m *Value) GetBytesValue() []byte {
	if x, ok := m.GetValue().(*Value_BytesValue); ok {
		return x.BytesValue
	}
	return nil
}

func (m *Value) GetIntList() *IntList {
	if x, ok := m.GetValue().(*Value_IntList); ok {
		return x.IntList
	}
	return nil
}

func (m *Value) GetStringValue() string {
	if x, ok := m.GetValue().(*Value_StringValue); ok {
		return x.StringValue
	}
	return ""
}

func (m *Value) GetAccount() *Account {
	if x, ok := m.GetValue().(*Value_Account); ok {
		return x.Account
	}
	return nil
}

func (m *Value) GetContract() *Contract {
	if x, ok := m.GetValue().(*Value_Contract); ok {
		return x.Contract
	}
	return nil
}

func (m *Value) GetStringList() *StringList {
	if x, ok := m.GetValue().(*Value_StringList); ok {
		return x.StringList
	}
	return nil
}

func (m *Value) GetNamedKey() *NamedKey {
	if x, ok := m.GetValue().(*Value_NamedKey); ok {
		return x.NamedKey
	}
	return nil
}

func (m *Value) GetBigInt() *BigInt {
	if x, ok := m.GetValue().(*Value_BigInt); ok {
		return x.BigInt
	}
	return nil
}

func (m *Value) GetKey() *Key {
	if x, ok := m.GetValue().(*Value_Key); ok {
		return x.Key
	}
	return nil
}

func (m *Value) GetUnit() *Unit {
	if x, ok := m.GetValue().(*Value_Unit); ok {
		return x.Unit
	}
	return nil
}

func (m *Value) GetLongValue() uint64 {
	if x, ok := m.GetValue().(*Value_LongValue); ok {
		return x.LongValue
	}
	return 0
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Value) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Value_IntValue)(nil),
		(*Value_BytesValue)(nil),
		(*Value_IntList)(nil),
		(*Value_StringValue)(nil),
		(*Value_Account)(nil),
		(*Value_Contract)(nil),
		(*Value_StringList)(nil),
		(*Value_NamedKey)(nil),
		(*Value_BigInt)(nil),
		(*Value_Key)(nil),
		(*Value_Unit)(nil),
		(*Value_LongValue)(nil),
	}
}

type IntList struct {
	Values               []int32  `protobuf:"varint,1,rep,packed,name=values,proto3" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IntList) Reset()         { *m = IntList{} }
func (m *IntList) String() string { return proto.CompactTextString(m) }
func (*IntList) ProtoMessage()    {}
func (*IntList) Descriptor() ([]byte, []int) {
	return fileDescriptor_bc5c211b7c38b10a, []int{4}
}
func (m *IntList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IntList.Unmarshal(m, b)
}
func (m *IntList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IntList.Marshal(b, m, deterministic)
}
func (m *IntList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IntList.Merge(m, src)
}
func (m *IntList) XXX_Size() int {
	return xxx_messageInfo_IntList.Size(m)
}
func (m *IntList) XXX_DiscardUnknown() {
	xxx_messageInfo_IntList.DiscardUnknown(m)
}

var xxx_messageInfo_IntList proto.InternalMessageInfo

func (m *IntList) GetValues() []int32 {
	if m != nil {
		return m.Values
	}
	return nil
}

type StringList struct {
	Values               []string `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StringList) Reset()         { *m = StringList{} }
func (m *StringList) String() string { return proto.CompactTextString(m) }
func (*StringList) ProtoMessage()    {}
func (*StringList) Descriptor() ([]byte, []int) {
	return fileDescriptor_bc5c211b7c38b10a, []int{5}
}
func (m *StringList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StringList.Unmarshal(m, b)
}
func (m *StringList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StringList.Marshal(b, m, deterministic)
}
func (m *StringList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StringList.Merge(m, src)
}
func (m *StringList) XXX_Size() int {
	return xxx_messageInfo_StringList.Size(m)
}
func (m *StringList) XXX_DiscardUnknown() {
	xxx_messageInfo_StringList.DiscardUnknown(m)
}

var xxx_messageInfo_StringList proto.InternalMessageInfo

func (m *StringList) GetValues() []string {
	if m != nil {
		return m.Values
	}
	return nil
}

type BigInt struct {
	Value string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	// Number of bits: 128 | 256 | 512.
	BitWidth             uint32   `protobuf:"varint,2,opt,name=bit_width,json=bitWidth,proto3" json:"bit_width,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BigInt) Reset()         { *m = BigInt{} }
func (m *BigInt) String() string { return proto.CompactTextString(m) }
func (*BigInt) ProtoMessage()    {}
func (*BigInt) Descriptor() ([]byte, []int) {
	return fileDescriptor_bc5c211b7c38b10a, []int{6}
}
func (m *BigInt) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BigInt.Unmarshal(m, b)
}
func (m *BigInt) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BigInt.Marshal(b, m, deterministic)
}
func (m *BigInt) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BigInt.Merge(m, src)
}
func (m *BigInt) XXX_Size() int {
	return xxx_messageInfo_BigInt.Size(m)
}
func (m *BigInt) XXX_DiscardUnknown() {
	xxx_messageInfo_BigInt.DiscardUnknown(m)
}

var xxx_messageInfo_BigInt proto.InternalMessageInfo

func (m *BigInt) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *BigInt) GetBitWidth() uint32 {
	if m != nil {
		return m.BitWidth
	}
	return 0
}

type Key struct {
	// Types that are valid to be assigned to Value:
	//	*Key_Address_
	//	*Key_Hash_
	//	*Key_Uref
	//	*Key_Local_
	Value                isKey_Value `protobuf_oneof:"value"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Key) Reset()         { *m = Key{} }
func (m *Key) String() string { return proto.CompactTextString(m) }
func (*Key) ProtoMessage()    {}
func (*Key) Descriptor() ([]byte, []int) {
	return fileDescriptor_bc5c211b7c38b10a, []int{7}
}
func (m *Key) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Key.Unmarshal(m, b)
}
func (m *Key) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Key.Marshal(b, m, deterministic)
}
func (m *Key) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Key.Merge(m, src)
}
func (m *Key) XXX_Size() int {
	return xxx_messageInfo_Key.Size(m)
}
func (m *Key) XXX_DiscardUnknown() {
	xxx_messageInfo_Key.DiscardUnknown(m)
}

var xxx_messageInfo_Key proto.InternalMessageInfo

type isKey_Value interface {
	isKey_Value()
}

type Key_Address_ struct {
	Address *Key_Address `protobuf:"bytes,1,opt,name=address,proto3,oneof" json:"address,omitempty"`
}
type Key_Hash_ struct {
	Hash *Key_Hash `protobuf:"bytes,2,opt,name=hash,proto3,oneof" json:"hash,omitempty"`
}
type Key_Uref struct {
	Uref *Key_URef `protobuf:"bytes,3,opt,name=uref,proto3,oneof" json:"uref,omitempty"`
}
type Key_Local_ struct {
	Local *Key_Local `protobuf:"bytes,4,opt,name=local,proto3,oneof" json:"local,omitempty"`
}

func (*Key_Address_) isKey_Value() {}
func (*Key_Hash_) isKey_Value()    {}
func (*Key_Uref) isKey_Value()     {}
func (*Key_Local_) isKey_Value()   {}

func (m *Key) GetValue() isKey_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *Key) GetAddress() *Key_Address {
	if x, ok := m.GetValue().(*Key_Address_); ok {
		return x.Address
	}
	return nil
}

func (m *Key) GetHash() *Key_Hash {
	if x, ok := m.GetValue().(*Key_Hash_); ok {
		return x.Hash
	}
	return nil
}

func (m *Key) GetUref() *Key_URef {
	if x, ok := m.GetValue().(*Key_Uref); ok {
		return x.Uref
	}
	return nil
}

func (m *Key) GetLocal() *Key_Local {
	if x, ok := m.GetValue().(*Key_Local_); ok {
		return x.Local
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Key) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Key_Address_)(nil),
		(*Key_Hash_)(nil),
		(*Key_Uref)(nil),
		(*Key_Local_)(nil),
	}
}

type Key_Address struct {
	Account              []byte   `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Key_Address) Reset()         { *m = Key_Address{} }
func (m *Key_Address) String() string { return proto.CompactTextString(m) }
func (*Key_Address) ProtoMessage()    {}
func (*Key_Address) Descriptor() ([]byte, []int) {
	return fileDescriptor_bc5c211b7c38b10a, []int{7, 0}
}
func (m *Key_Address) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Key_Address.Unmarshal(m, b)
}
func (m *Key_Address) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Key_Address.Marshal(b, m, deterministic)
}
func (m *Key_Address) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Key_Address.Merge(m, src)
}
func (m *Key_Address) XXX_Size() int {
	return xxx_messageInfo_Key_Address.Size(m)
}
func (m *Key_Address) XXX_DiscardUnknown() {
	xxx_messageInfo_Key_Address.DiscardUnknown(m)
}

var xxx_messageInfo_Key_Address proto.InternalMessageInfo

func (m *Key_Address) GetAccount() []byte {
	if m != nil {
		return m.Account
	}
	return nil
}

type Key_Hash struct {
	Hash                 []byte   `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Key_Hash) Reset()         { *m = Key_Hash{} }
func (m *Key_Hash) String() string { return proto.CompactTextString(m) }
func (*Key_Hash) ProtoMessage()    {}
func (*Key_Hash) Descriptor() ([]byte, []int) {
	return fileDescriptor_bc5c211b7c38b10a, []int{7, 1}
}
func (m *Key_Hash) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Key_Hash.Unmarshal(m, b)
}
func (m *Key_Hash) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Key_Hash.Marshal(b, m, deterministic)
}
func (m *Key_Hash) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Key_Hash.Merge(m, src)
}
func (m *Key_Hash) XXX_Size() int {
	return xxx_messageInfo_Key_Hash.Size(m)
}
func (m *Key_Hash) XXX_DiscardUnknown() {
	xxx_messageInfo_Key_Hash.DiscardUnknown(m)
}

var xxx_messageInfo_Key_Hash proto.InternalMessageInfo

func (m *Key_Hash) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

type Key_URef struct {
	Uref                 []byte                `protobuf:"bytes,1,opt,name=uref,proto3" json:"uref,omitempty"`
	AccessRights         Key_URef_AccessRights `protobuf:"varint,2,opt,name=access_rights,json=accessRights,proto3,enum=io.casperlabs.casper.consensus.state.Key_URef_AccessRights" json:"access_rights,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *Key_URef) Reset()         { *m = Key_URef{} }
func (m *Key_URef) String() string { return proto.CompactTextString(m) }
func (*Key_URef) ProtoMessage()    {}
func (*Key_URef) Descriptor() ([]byte, []int) {
	return fileDescriptor_bc5c211b7c38b10a, []int{7, 2}
}
func (m *Key_URef) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Key_URef.Unmarshal(m, b)
}
func (m *Key_URef) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Key_URef.Marshal(b, m, deterministic)
}
func (m *Key_URef) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Key_URef.Merge(m, src)
}
func (m *Key_URef) XXX_Size() int {
	return xxx_messageInfo_Key_URef.Size(m)
}
func (m *Key_URef) XXX_DiscardUnknown() {
	xxx_messageInfo_Key_URef.DiscardUnknown(m)
}

var xxx_messageInfo_Key_URef proto.InternalMessageInfo

func (m *Key_URef) GetUref() []byte {
	if m != nil {
		return m.Uref
	}
	return nil
}

func (m *Key_URef) GetAccessRights() Key_URef_AccessRights {
	if m != nil {
		return m.AccessRights
	}
	return Key_URef_UNKNOWN
}

type Key_Local struct {
	Hash                 []byte   `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Key_Local) Reset()         { *m = Key_Local{} }
func (m *Key_Local) String() string { return proto.CompactTextString(m) }
func (*Key_Local) ProtoMessage()    {}
func (*Key_Local) Descriptor() ([]byte, []int) {
	return fileDescriptor_bc5c211b7c38b10a, []int{7, 3}
}
func (m *Key_Local) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Key_Local.Unmarshal(m, b)
}
func (m *Key_Local) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Key_Local.Marshal(b, m, deterministic)
}
func (m *Key_Local) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Key_Local.Merge(m, src)
}
func (m *Key_Local) XXX_Size() int {
	return xxx_messageInfo_Key_Local.Size(m)
}
func (m *Key_Local) XXX_DiscardUnknown() {
	xxx_messageInfo_Key_Local.DiscardUnknown(m)
}

var xxx_messageInfo_Key_Local proto.InternalMessageInfo

func (m *Key_Local) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

type NamedKey struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Key                  *Key     `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NamedKey) Reset()         { *m = NamedKey{} }
func (m *NamedKey) String() string { return proto.CompactTextString(m) }
func (*NamedKey) ProtoMessage()    {}
func (*NamedKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_bc5c211b7c38b10a, []int{8}
}
func (m *NamedKey) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NamedKey.Unmarshal(m, b)
}
func (m *NamedKey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NamedKey.Marshal(b, m, deterministic)
}
func (m *NamedKey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NamedKey.Merge(m, src)
}
func (m *NamedKey) XXX_Size() int {
	return xxx_messageInfo_NamedKey.Size(m)
}
func (m *NamedKey) XXX_DiscardUnknown() {
	xxx_messageInfo_NamedKey.DiscardUnknown(m)
}

var xxx_messageInfo_NamedKey proto.InternalMessageInfo

func (m *NamedKey) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *NamedKey) GetKey() *Key {
	if m != nil {
		return m.Key
	}
	return nil
}

type Contract struct {
	Body                 []byte           `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
	NamedKeys            []*NamedKey      `protobuf:"bytes,2,rep,name=named_keys,json=namedKeys,proto3" json:"named_keys,omitempty"`
	ProtocolVersion      *ProtocolVersion `protobuf:"bytes,3,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Contract) Reset()         { *m = Contract{} }
func (m *Contract) String() string { return proto.CompactTextString(m) }
func (*Contract) ProtoMessage()    {}
func (*Contract) Descriptor() ([]byte, []int) {
	return fileDescriptor_bc5c211b7c38b10a, []int{9}
}
func (m *Contract) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Contract.Unmarshal(m, b)
}
func (m *Contract) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Contract.Marshal(b, m, deterministic)
}
func (m *Contract) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Contract.Merge(m, src)
}
func (m *Contract) XXX_Size() int {
	return xxx_messageInfo_Contract.Size(m)
}
func (m *Contract) XXX_DiscardUnknown() {
	xxx_messageInfo_Contract.DiscardUnknown(m)
}

var xxx_messageInfo_Contract proto.InternalMessageInfo

func (m *Contract) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

func (m *Contract) GetNamedKeys() []*NamedKey {
	if m != nil {
		return m.NamedKeys
	}
	return nil
}

func (m *Contract) GetProtocolVersion() *ProtocolVersion {
	if m != nil {
		return m.ProtocolVersion
	}
	return nil
}

type Account struct {
	PublicKey            []byte                    `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	PurseId              *Key_URef                 `protobuf:"bytes,3,opt,name=purse_id,json=purseId,proto3" json:"purse_id,omitempty"`
	NamedKeys            []*NamedKey               `protobuf:"bytes,4,rep,name=named_keys,json=namedKeys,proto3" json:"named_keys,omitempty"`
	AssociatedKeys       []*Account_AssociatedKey  `protobuf:"bytes,5,rep,name=associated_keys,json=associatedKeys,proto3" json:"associated_keys,omitempty"`
	ActionThresholds     *Account_ActionThresholds `protobuf:"bytes,6,opt,name=action_thresholds,json=actionThresholds,proto3" json:"action_thresholds,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *Account) Reset()         { *m = Account{} }
func (m *Account) String() string { return proto.CompactTextString(m) }
func (*Account) ProtoMessage()    {}
func (*Account) Descriptor() ([]byte, []int) {
	return fileDescriptor_bc5c211b7c38b10a, []int{10}
}
func (m *Account) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Account.Unmarshal(m, b)
}
func (m *Account) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Account.Marshal(b, m, deterministic)
}
func (m *Account) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Account.Merge(m, src)
}
func (m *Account) XXX_Size() int {
	return xxx_messageInfo_Account.Size(m)
}
func (m *Account) XXX_DiscardUnknown() {
	xxx_messageInfo_Account.DiscardUnknown(m)
}

var xxx_messageInfo_Account proto.InternalMessageInfo

func (m *Account) GetPublicKey() []byte {
	if m != nil {
		return m.PublicKey
	}
	return nil
}

func (m *Account) GetPurseId() *Key_URef {
	if m != nil {
		return m.PurseId
	}
	return nil
}

func (m *Account) GetNamedKeys() []*NamedKey {
	if m != nil {
		return m.NamedKeys
	}
	return nil
}

func (m *Account) GetAssociatedKeys() []*Account_AssociatedKey {
	if m != nil {
		return m.AssociatedKeys
	}
	return nil
}

func (m *Account) GetActionThresholds() *Account_ActionThresholds {
	if m != nil {
		return m.ActionThresholds
	}
	return nil
}

type Account_AssociatedKey struct {
	PublicKey            []byte   `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	Weight               uint32   `protobuf:"varint,2,opt,name=weight,proto3" json:"weight,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Account_AssociatedKey) Reset()         { *m = Account_AssociatedKey{} }
func (m *Account_AssociatedKey) String() string { return proto.CompactTextString(m) }
func (*Account_AssociatedKey) ProtoMessage()    {}
func (*Account_AssociatedKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_bc5c211b7c38b10a, []int{10, 0}
}
func (m *Account_AssociatedKey) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Account_AssociatedKey.Unmarshal(m, b)
}
func (m *Account_AssociatedKey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Account_AssociatedKey.Marshal(b, m, deterministic)
}
func (m *Account_AssociatedKey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Account_AssociatedKey.Merge(m, src)
}
func (m *Account_AssociatedKey) XXX_Size() int {
	return xxx_messageInfo_Account_AssociatedKey.Size(m)
}
func (m *Account_AssociatedKey) XXX_DiscardUnknown() {
	xxx_messageInfo_Account_AssociatedKey.DiscardUnknown(m)
}

var xxx_messageInfo_Account_AssociatedKey proto.InternalMessageInfo

func (m *Account_AssociatedKey) GetPublicKey() []byte {
	if m != nil {
		return m.PublicKey
	}
	return nil
}

func (m *Account_AssociatedKey) GetWeight() uint32 {
	if m != nil {
		return m.Weight
	}
	return 0
}

type Account_ActionThresholds struct {
	DeploymentThreshold    uint32   `protobuf:"varint,1,opt,name=deployment_threshold,json=deploymentThreshold,proto3" json:"deployment_threshold,omitempty"`
	KeyManagementThreshold uint32   `protobuf:"varint,2,opt,name=key_management_threshold,json=keyManagementThreshold,proto3" json:"key_management_threshold,omitempty"`
	XXX_NoUnkeyedLiteral   struct{} `json:"-"`
	XXX_unrecognized       []byte   `json:"-"`
	XXX_sizecache          int32    `json:"-"`
}

func (m *Account_ActionThresholds) Reset()         { *m = Account_ActionThresholds{} }
func (m *Account_ActionThresholds) String() string { return proto.CompactTextString(m) }
func (*Account_ActionThresholds) ProtoMessage()    {}
func (*Account_ActionThresholds) Descriptor() ([]byte, []int) {
	return fileDescriptor_bc5c211b7c38b10a, []int{10, 1}
}
func (m *Account_ActionThresholds) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Account_ActionThresholds.Unmarshal(m, b)
}
func (m *Account_ActionThresholds) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Account_ActionThresholds.Marshal(b, m, deterministic)
}
func (m *Account_ActionThresholds) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Account_ActionThresholds.Merge(m, src)
}
func (m *Account_ActionThresholds) XXX_Size() int {
	return xxx_messageInfo_Account_ActionThresholds.Size(m)
}
func (m *Account_ActionThresholds) XXX_DiscardUnknown() {
	xxx_messageInfo_Account_ActionThresholds.DiscardUnknown(m)
}

var xxx_messageInfo_Account_ActionThresholds proto.InternalMessageInfo

func (m *Account_ActionThresholds) GetDeploymentThreshold() uint32 {
	if m != nil {
		return m.DeploymentThreshold
	}
	return 0
}

func (m *Account_ActionThresholds) GetKeyManagementThreshold() uint32 {
	if m != nil {
		return m.KeyManagementThreshold
	}
	return 0
}

type Unit struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Unit) Reset()         { *m = Unit{} }
func (m *Unit) String() string { return proto.CompactTextString(m) }
func (*Unit) ProtoMessage()    {}
func (*Unit) Descriptor() ([]byte, []int) {
	return fileDescriptor_bc5c211b7c38b10a, []int{11}
}
func (m *Unit) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Unit.Unmarshal(m, b)
}
func (m *Unit) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Unit.Marshal(b, m, deterministic)
}
func (m *Unit) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Unit.Merge(m, src)
}
func (m *Unit) XXX_Size() int {
	return xxx_messageInfo_Unit.Size(m)
}
func (m *Unit) XXX_DiscardUnknown() {
	xxx_messageInfo_Unit.DiscardUnknown(m)
}

var xxx_messageInfo_Unit proto.InternalMessageInfo

type ProtocolVersion struct {
	Major                uint32   `protobuf:"varint,1,opt,name=major,proto3" json:"major,omitempty"`
	Minor                uint32   `protobuf:"varint,2,opt,name=minor,proto3" json:"minor,omitempty"`
	Patch                uint32   `protobuf:"varint,3,opt,name=patch,proto3" json:"patch,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProtocolVersion) Reset()         { *m = ProtocolVersion{} }
func (m *ProtocolVersion) String() string { return proto.CompactTextString(m) }
func (*ProtocolVersion) ProtoMessage()    {}
func (*ProtocolVersion) Descriptor() ([]byte, []int) {
	return fileDescriptor_bc5c211b7c38b10a, []int{12}
}
func (m *ProtocolVersion) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProtocolVersion.Unmarshal(m, b)
}
func (m *ProtocolVersion) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProtocolVersion.Marshal(b, m, deterministic)
}
func (m *ProtocolVersion) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProtocolVersion.Merge(m, src)
}
func (m *ProtocolVersion) XXX_Size() int {
	return xxx_messageInfo_ProtocolVersion.Size(m)
}
func (m *ProtocolVersion) XXX_DiscardUnknown() {
	xxx_messageInfo_ProtocolVersion.DiscardUnknown(m)
}

var xxx_messageInfo_ProtocolVersion proto.InternalMessageInfo

func (m *ProtocolVersion) GetMajor() uint32 {
	if m != nil {
		return m.Major
	}
	return 0
}

func (m *ProtocolVersion) GetMinor() uint32 {
	if m != nil {
		return m.Minor
	}
	return 0
}

func (m *ProtocolVersion) GetPatch() uint32 {
	if m != nil {
		return m.Patch
	}
	return 0
}

func init() {
	proto.RegisterEnum("io.casperlabs.casper.consensus.state.CLType_Simple", CLType_Simple_name, CLType_Simple_value)
	proto.RegisterEnum("io.casperlabs.casper.consensus.state.Key_URef_AccessRights", Key_URef_AccessRights_name, Key_URef_AccessRights_value)
	proto.RegisterType((*CLType)(nil), "io.casperlabs.casper.consensus.state.CLType")
	proto.RegisterType((*CLType_Option)(nil), "io.casperlabs.casper.consensus.state.CLType.Option")
	proto.RegisterType((*CLType_List)(nil), "io.casperlabs.casper.consensus.state.CLType.List")
	proto.RegisterType((*CLType_FixedList)(nil), "io.casperlabs.casper.consensus.state.CLType.FixedList")
	proto.RegisterType((*CLType_Result)(nil), "io.casperlabs.casper.consensus.state.CLType.Result")
	proto.RegisterType((*CLType_Map)(nil), "io.casperlabs.casper.consensus.state.CLType.Map")
	proto.RegisterType((*CLType_Tuple1)(nil), "io.casperlabs.casper.consensus.state.CLType.Tuple1")
	proto.RegisterType((*CLType_Tuple2)(nil), "io.casperlabs.casper.consensus.state.CLType.Tuple2")
	proto.RegisterType((*CLType_Tuple3)(nil), "io.casperlabs.casper.consensus.state.CLType.Tuple3")
	proto.RegisterType((*CLType_Any)(nil), "io.casperlabs.casper.consensus.state.CLType.Any")
	proto.RegisterType((*CLValue)(nil), "io.casperlabs.casper.consensus.state.CLValue")
	proto.RegisterType((*StoredValue)(nil), "io.casperlabs.casper.consensus.state.StoredValue")
	proto.RegisterType((*Value)(nil), "io.casperlabs.casper.consensus.state.Value")
	proto.RegisterType((*IntList)(nil), "io.casperlabs.casper.consensus.state.IntList")
	proto.RegisterType((*StringList)(nil), "io.casperlabs.casper.consensus.state.StringList")
	proto.RegisterType((*BigInt)(nil), "io.casperlabs.casper.consensus.state.BigInt")
	proto.RegisterType((*Key)(nil), "io.casperlabs.casper.consensus.state.Key")
	proto.RegisterType((*Key_Address)(nil), "io.casperlabs.casper.consensus.state.Key.Address")
	proto.RegisterType((*Key_Hash)(nil), "io.casperlabs.casper.consensus.state.Key.Hash")
	proto.RegisterType((*Key_URef)(nil), "io.casperlabs.casper.consensus.state.Key.URef")
	proto.RegisterType((*Key_Local)(nil), "io.casperlabs.casper.consensus.state.Key.Local")
	proto.RegisterType((*NamedKey)(nil), "io.casperlabs.casper.consensus.state.NamedKey")
	proto.RegisterType((*Contract)(nil), "io.casperlabs.casper.consensus.state.Contract")
	proto.RegisterType((*Account)(nil), "io.casperlabs.casper.consensus.state.Account")
	proto.RegisterType((*Account_AssociatedKey)(nil), "io.casperlabs.casper.consensus.state.Account.AssociatedKey")
	proto.RegisterType((*Account_ActionThresholds)(nil), "io.casperlabs.casper.consensus.state.Account.ActionThresholds")
	proto.RegisterType((*Unit)(nil), "io.casperlabs.casper.consensus.state.Unit")
	proto.RegisterType((*ProtocolVersion)(nil), "io.casperlabs.casper.consensus.state.ProtocolVersion")
}

func init() {
	proto.RegisterFile("io/casperlabs/casper/consensus/state/state.proto", fileDescriptor_bc5c211b7c38b10a)
}

var fileDescriptor_bc5c211b7c38b10a = []byte{
	// 1544 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x98, 0xcd, 0x6e, 0xdb, 0x46,
	0x10, 0xc7, 0x45, 0x49, 0xfc, 0x1a, 0xc9, 0x36, 0xbb, 0x0d, 0x02, 0x43, 0x41, 0x50, 0x47, 0xc9,
	0xc1, 0x29, 0x6a, 0x39, 0x96, 0x12, 0x23, 0x80, 0xdb, 0xa0, 0x72, 0xec, 0xc4, 0x72, 0xfc, 0x11,
	0xd0, 0x76, 0x82, 0x36, 0x28, 0x94, 0x15, 0xb5, 0x96, 0xb6, 0xa6, 0x48, 0x82, 0x4b, 0x25, 0x55,
	0x7a, 0xe8, 0xa9, 0x05, 0x8a, 0x5e, 0xfa, 0x66, 0xb9, 0xf4, 0x29, 0xda, 0x17, 0xe8, 0xa9, 0x28,
	0xf6, 0x83, 0x92, 0xed, 0x16, 0xa8, 0xa8, 0xf8, 0xd0, 0x8b, 0xb1, 0xb3, 0xcb, 0xff, 0x8f, 0xb3,
	0xc3, 0xd9, 0x99, 0xb5, 0xe0, 0x1e, 0x0d, 0x57, 0x3d, 0xcc, 0x22, 0x12, 0xfb, 0xb8, 0xc3, 0xd4,
	0x70, 0xd5, 0x0b, 0x03, 0x46, 0x02, 0x36, 0x64, 0xab, 0x2c, 0xc1, 0x09, 0x91, 0x7f, 0x6b, 0x51,
	0x1c, 0x26, 0x21, 0xba, 0x43, 0xc3, 0xda, 0x44, 0xa1, 0x86, 0xb5, 0xb1, 0xa2, 0x26, 0x9e, 0xad,
	0xbe, 0x5f, 0x00, 0xe3, 0xf1, 0xde, 0xf1, 0x28, 0x22, 0xe8, 0x05, 0x94, 0x18, 0x1d, 0x44, 0x3e,
	0x69, 0x27, 0xa3, 0x88, 0x2c, 0x6a, 0x4b, 0xda, 0xf2, 0x7c, 0xbd, 0x51, 0x9b, 0x06, 0x53, 0x93,
	0x88, 0xda, 0x91, 0xd0, 0xef, 0xe4, 0x5c, 0x90, 0xa4, 0x94, 0x1b, 0x46, 0x09, 0x0d, 0x03, 0xc9,
	0xcd, 0x2f, 0x69, 0xcb, 0xa5, 0x8c, 0xdc, 0x43, 0xa1, 0xe7, 0x5c, 0x49, 0x12, 0xdc, 0xe7, 0x60,
	0xfb, 0x94, 0x25, 0x92, 0x5a, 0x10, 0xd4, 0xb5, 0x4c, 0xd4, 0x3d, 0xca, 0x92, 0x9d, 0x9c, 0x6b,
	0x71, 0x8a, 0x20, 0xbe, 0x86, 0x85, 0x53, 0xfa, 0x1d, 0xe9, 0xb6, 0x27, 0xdc, 0xa2, 0xe0, 0xae,
	0x67, 0xe2, 0x3e, 0xe1, 0x0c, 0x05, 0x9f, 0x3b, 0x4d, 0x8d, 0x34, 0x16, 0x31, 0x61, 0x43, 0x5f,
	0xd1, 0xf5, 0x19, 0x62, 0xe1, 0x0a, 0x3d, 0x8f, 0x85, 0x24, 0x09, 0xee, 0x3e, 0x58, 0x03, 0x1c,
	0x49, 0xa8, 0x21, 0xa0, 0xf7, 0x32, 0x41, 0xf7, 0x71, 0xb4, 0x93, 0x73, 0xcd, 0x01, 0x8e, 0x52,
	0x37, 0x93, 0x61, 0xe4, 0x93, 0x35, 0x49, 0x34, 0x67, 0x70, 0xf3, 0x58, 0xe8, 0xb9, 0x9b, 0x92,
	0x74, 0x81, 0x5b, 0x97, 0x5c, 0x6b, 0x56, 0x6e, 0x7d, 0xcc, 0xad, 0x5f, 0xe0, 0x36, 0x24, 0xd7,
	0x9e, 0x95, 0xdb, 0x18, 0x73, 0x1b, 0x69, 0x58, 0x71, 0x30, 0x92, 0x50, 0x98, 0x21, 0xac, 0xcd,
	0x60, 0xc4, 0xc3, 0x8a, 0x83, 0x11, 0x37, 0x2b, 0x7b, 0x60, 0xc8, 0x4c, 0x46, 0x9b, 0xa0, 0xd3,
	0x20, 0x20, 0xb1, 0x38, 0x65, 0xa5, 0xfa, 0x67, 0x59, 0xa8, 0xae, 0x94, 0x56, 0x76, 0xa1, 0xc8,
	0xf3, 0xea, 0x4a, 0x58, 0x18, 0xec, 0x71, 0xd6, 0x5e, 0x05, 0x10, 0x39, 0x50, 0xf0, 0x49, 0x20,
	0x0e, 0xfb, 0x9c, 0xcb, 0x87, 0x95, 0x9f, 0x34, 0x30, 0x64, 0xee, 0xa2, 0xcf, 0x21, 0x1f, 0x9e,
	0xcd, 0x44, 0xcf, 0x87, 0x67, 0xe8, 0x11, 0x14, 0x48, 0x1c, 0xab, 0x3a, 0x92, 0x4d, 0xce, 0x85,
	0x95, 0x9f, 0x35, 0x28, 0xec, 0xe3, 0x88, 0x73, 0xce, 0xc8, 0x68, 0x26, 0x37, 0xb8, 0x90, 0x87,
	0xe9, 0x0d, 0xf6, 0x87, 0x64, 0x26, 0x4f, 0xa4, 0x94, 0x67, 0x84, 0x3c, 0x28, 0x9c, 0xc6, 0xd3,
	0xec, 0xde, 0x6c, 0x41, 0x17, 0xd2, 0xca, 0xaf, 0x9a, 0xc2, 0xd5, 0xaf, 0x02, 0x97, 0x32, 0xd6,
	0x66, 0xdb, 0xa0, 0x90, 0x56, 0x7e, 0x4b, 0x5d, 0x6a, 0xfc, 0x5f, 0x5c, 0x4a, 0x19, 0x75, 0xd5,
	0x33, 0x66, 0x60, 0xd4, 0x2b, 0x3a, 0x14, 0x9a, 0xc1, 0xa8, 0xfa, 0xa3, 0x06, 0x86, 0xec, 0x79,
	0xc8, 0x82, 0xe2, 0xe6, 0xe1, 0xe1, 0x9e, 0x93, 0x43, 0x26, 0x14, 0x5a, 0x8d, 0xba, 0xa3, 0x89,
	0xc1, 0xfa, 0x7d, 0x27, 0x8f, 0x0c, 0xc8, 0x9f, 0x3c, 0x74, 0x0a, 0x7c, 0xe2, 0xa4, 0x51, 0x77,
	0x8a, 0x62, 0xb0, 0x7e, 0xdf, 0xd1, 0xb9, 0xea, 0x64, 0xad, 0xfe, 0xd0, 0x31, 0xc4, 0xa8, 0xfe,
	0x60, 0xdd, 0x31, 0xc5, 0xe8, 0xc1, 0x5a, 0xdd, 0xb1, 0xc4, 0xe8, 0xa0, 0x75, 0xec, 0xd8, 0x08,
	0xc0, 0x38, 0x3a, 0x76, 0x5b, 0x07, 0x4f, 0x1d, 0xe0, 0xe2, 0x67, 0xdb, 0x5f, 0x39, 0x25, 0xb1,
	0xec, 0x6e, 0x3f, 0x71, 0xca, 0x9b, 0x00, 0xd6, 0x1b, 0x1c, 0x53, 0x1c, 0x24, 0xac, 0xfa, 0x3d,
	0x98, 0x8f, 0xf7, 0x5e, 0xf0, 0xec, 0x42, 0xdb, 0x60, 0x7a, 0xfe, 0xa4, 0x9b, 0x67, 0xdd, 0xab,
	0xe1, 0xf9, 0xa2, 0x0a, 0xde, 0x05, 0x87, 0x91, 0x98, 0x62, 0x9f, 0xbe, 0x23, 0xdd, 0xf6, 0x24,
	0xe7, 0xcb, 0xee, 0xc2, 0x64, 0x5e, 0xbc, 0xb1, 0xfa, 0x97, 0x06, 0xa5, 0xa3, 0x24, 0x8c, 0x95,
	0x8d, 0x76, 0xc1, 0xf2, 0x7c, 0x25, 0x91, 0x2e, 0xac, 0x4c, 0xeb, 0x82, 0x00, 0xf0, 0xea, 0xe9,
	0xf9, 0x92, 0xd5, 0x02, 0x13, 0x7b, 0x5e, 0x38, 0x0c, 0x12, 0xf5, 0xf5, 0xa7, 0x44, 0x35, 0xa5,
	0x48, 0x14, 0x62, 0x39, 0x44, 0x7b, 0x60, 0x79, 0x61, 0x90, 0xc4, 0xd8, 0x4b, 0x54, 0x16, 0xd4,
	0xa6, 0x74, 0x4b, 0xa9, 0xf8, 0xb5, 0x21, 0x25, 0x5c, 0x88, 0xfe, 0x1f, 0x3a, 0xe8, 0xd2, 0xdd,
	0x9b, 0x60, 0xd3, 0x20, 0x39, 0xb7, 0x77, 0x9d, 0x8b, 0x68, 0x90, 0xc8, 0xe5, 0x5b, 0x50, 0xea,
	0x8c, 0x12, 0xc2, 0xce, 0xc7, 0x93, 0x77, 0x1f, 0x31, 0x39, 0x0e, 0x1e, 0x27, 0xf0, 0xcb, 0x88,
	0xf2, 0x72, 0xca, 0x1d, 0xb7, 0x82, 0x44, 0x5d, 0x3f, 0x4c, 0x2a, 0x87, 0xe8, 0x36, 0x94, 0x59,
	0x12, 0xd3, 0xa0, 0xa7, 0xde, 0xc7, 0xef, 0x35, 0xf6, 0x4e, 0xce, 0x2d, 0xc9, 0xd9, 0x7f, 0x44,
	0x58, 0xbf, 0xc2, 0x08, 0x1b, 0x1f, 0x1a, 0x61, 0x74, 0x04, 0xca, 0x4f, 0x19, 0x0c, 0x33, 0x4b,
	0x2b, 0x3e, 0x12, 0x42, 0x15, 0x0f, 0x60, 0x63, 0x0b, 0xed, 0x83, 0x1d, 0xe0, 0x01, 0xe9, 0xb6,
	0x79, 0x17, 0xb0, 0xb2, 0xf8, 0x78, 0xc0, 0x65, 0xcf, 0x08, 0xef, 0xed, 0x56, 0xa0, 0xc6, 0xe8,
	0x29, 0x98, 0x1d, 0xda, 0x6b, 0xd3, 0x20, 0x51, 0xf7, 0x8f, 0x29, 0x0f, 0xdb, 0x26, 0xed, 0xb5,
	0x44, 0xec, 0x8c, 0x8e, 0x18, 0xa1, 0x2f, 0x64, 0x5f, 0x92, 0xf7, 0x8d, 0xbb, 0xd3, 0x41, 0xa4,
	0x33, 0xa2, 0x2d, 0x7d, 0x09, 0xc5, 0x61, 0x40, 0x93, 0xc5, 0x92, 0xd0, 0x7f, 0x3a, 0x9d, 0xfe,
	0x24, 0xa0, 0xdc, 0x05, 0xa1, 0x44, 0x9f, 0x00, 0xf8, 0xe1, 0x38, 0x53, 0xca, 0x4b, 0xda, 0x72,
	0x71, 0x27, 0xe7, 0xda, 0x7c, 0x4e, 0xe4, 0xc9, 0xa6, 0xa9, 0x3a, 0x5f, 0xf5, 0x16, 0x98, 0x2a,
	0xd7, 0xd0, 0x75, 0x30, 0xc4, 0x1c, 0x5b, 0xd4, 0x96, 0x0a, 0xcb, 0xba, 0xab, 0xac, 0xea, 0x1d,
	0x80, 0xc9, 0x17, 0xb8, 0xf4, 0x94, 0x3d, 0x7e, 0x6a, 0x03, 0x0c, 0x19, 0x07, 0x74, 0x2d, 0xed,
	0xaa, 0xfc, 0xc8, 0xd8, 0xaa, 0x4f, 0xa2, 0x1b, 0x60, 0x77, 0x68, 0xd2, 0x7e, 0x4b, 0xbb, 0x49,
	0x5f, 0x5d, 0x2a, 0xac, 0x0e, 0x4d, 0x5e, 0x72, 0xbb, 0xfa, 0x8b, 0x0e, 0x05, 0xfe, 0x05, 0xf6,
	0xc1, 0xc4, 0xdd, 0x6e, 0x4c, 0x18, 0x53, 0xb5, 0x66, 0x6d, 0xea, 0xe0, 0xd5, 0x9a, 0x52, 0x28,
	0x52, 0x58, 0x0e, 0xd1, 0x16, 0x14, 0xfb, 0x98, 0xf5, 0x55, 0xb1, 0xa9, 0x4d, 0xcf, 0xda, 0xc1,
	0xac, 0xcf, 0x83, 0xc9, 0xd5, 0x9c, 0x32, 0x8c, 0xc9, 0x69, 0xb6, 0x32, 0xc3, 0x29, 0x27, 0x2e,
	0x39, 0x15, 0x9f, 0x24, 0x26, 0xa7, 0xe8, 0x29, 0xe8, 0x7e, 0xe8, 0x61, 0x5f, 0xfd, 0x3f, 0xb2,
	0x3a, 0x3d, 0x66, 0x8f, 0xcb, 0x76, 0x72, 0xae, 0xd4, 0x57, 0x6e, 0x83, 0xa9, 0xb6, 0x8a, 0x16,
	0x27, 0xa7, 0x5d, 0x13, 0xd5, 0x3c, 0x35, 0x2b, 0x15, 0x28, 0xf2, 0x3d, 0x20, 0xa4, 0x22, 0x20,
	0x97, 0xc5, 0xb8, 0xf2, 0xa7, 0xc6, 0xbb, 0x0e, 0x39, 0xe5, 0x8b, 0x62, 0x63, 0x6a, 0x51, 0xb8,
	0xf9, 0x1a, 0xe6, 0xb0, 0xe7, 0x11, 0xc6, 0xda, 0x31, 0xed, 0xf5, 0x13, 0x26, 0x62, 0x37, 0x5f,
	0xdf, 0xc8, 0xb6, 0x6b, 0x5e, 0x4f, 0x08, 0x63, 0xae, 0x40, 0xb8, 0x65, 0x7c, 0xce, 0xaa, 0xbe,
	0x83, 0xf2, 0xf9, 0x55, 0x54, 0x02, 0xf3, 0xe4, 0xe0, 0xd9, 0xc1, 0xe1, 0xcb, 0x03, 0x27, 0xc7,
	0x1b, 0xa2, 0xbb, 0xdd, 0xdc, 0x72, 0x34, 0x64, 0x83, 0xfe, 0xd2, 0x6d, 0x1d, 0x6f, 0x3b, 0x79,
	0xde, 0x2e, 0x9b, 0x5b, 0x5b, 0x4e, 0x11, 0x95, 0xc1, 0xe2, 0xab, 0x6d, 0x6e, 0xe9, 0x68, 0x1e,
	0x40, 0x58, 0xf2, 0xb1, 0x02, 0x9a, 0x03, 0xbb, 0xb9, 0x95, 0x9a, 0x06, 0x42, 0x30, 0x9f, 0x3e,
	0xac, 0xe6, 0xcc, 0xca, 0x0d, 0xd0, 0x45, 0x34, 0xff, 0x2d, 0x2e, 0x93, 0x33, 0xf1, 0x0a, 0xac,
	0xb4, 0x3e, 0xf0, 0x07, 0x79, 0x7d, 0x50, 0xb9, 0x2c, 0xc6, 0x68, 0x43, 0x1e, 0xef, 0x7c, 0xc6,
	0xe3, 0x2d, 0x0e, 0x77, 0xf5, 0xbd, 0x06, 0x56, 0x5a, 0x21, 0x39, 0xbd, 0x13, 0x76, 0x47, 0xa9,
	0x1b, 0x7c, 0x8c, 0xf6, 0x01, 0xc6, 0x45, 0x8d, 0x87, 0xbf, 0x90, 0xbd, 0xaa, 0xb9, 0x76, 0x5a,
	0xd3, 0x18, 0x7a, 0x0d, 0x8e, 0xf8, 0x35, 0xc1, 0x0b, 0xfd, 0xf6, 0x1b, 0x12, 0x33, 0x1a, 0x06,
	0x2a, 0x93, 0x1f, 0x4c, 0x07, 0x7d, 0xae, 0xd4, 0x2f, 0xa4, 0xd8, 0x5d, 0x88, 0x2e, 0x4e, 0x54,
	0x7f, 0x2f, 0x82, 0xa9, 0xfa, 0x07, 0xba, 0x09, 0x10, 0x0d, 0x3b, 0x3e, 0xf5, 0xda, 0xe9, 0xc5,
	0xbc, 0xec, 0xda, 0x72, 0x86, 0x47, 0xb3, 0x05, 0x56, 0x34, 0x8c, 0x19, 0x69, 0xd3, 0xee, 0x6c,
	0xc7, 0xc9, 0x35, 0x85, 0xbe, 0xd5, 0xbd, 0x14, 0xa6, 0xe2, 0x87, 0x86, 0xa9, 0x0b, 0x0b, 0x98,
	0xb1, 0xd0, 0xa3, 0x38, 0x49, 0x99, 0xba, 0x60, 0x6e, 0x64, 0x6a, 0xa0, 0xb5, 0xe6, 0x18, 0xc2,
	0x5f, 0x30, 0x8f, 0xcf, 0x9b, 0x0c, 0x9d, 0xc1, 0x47, 0xd8, 0x93, 0x3f, 0xa4, 0xf4, 0x63, 0xc2,
	0xfa, 0xa1, 0xdf, 0x65, 0xaa, 0xb9, 0x3e, 0xca, 0xf8, 0x1e, 0x81, 0x39, 0x1e, 0x53, 0x5c, 0x07,
	0x5f, 0x9a, 0xa9, 0x3c, 0x81, 0xb9, 0x0b, 0xde, 0xfc, 0xd7, 0xc7, 0xb9, 0x0e, 0xc6, 0x5b, 0xc2,
	0xcf, 0xa4, 0x2a, 0xcf, 0xca, 0xaa, 0xfc, 0x00, 0xce, 0xe5, 0xb7, 0xa1, 0x35, 0xb8, 0xd6, 0x25,
	0x91, 0x1f, 0x8e, 0x06, 0x24, 0x48, 0x26, 0x9b, 0x11, 0xd0, 0x39, 0xf7, 0xe3, 0xc9, 0xda, 0x58,
	0x83, 0x1e, 0xc2, 0xe2, 0x19, 0x19, 0xb5, 0x07, 0x38, 0xc0, 0x3d, 0x72, 0x49, 0x26, 0x5f, 0x78,
	0xfd, 0x8c, 0x8c, 0xf6, 0xc7, 0xcb, 0x63, 0xe5, 0x6e, 0xd1, 0xca, 0x3b, 0x85, 0xdd, 0xa2, 0x65,
	0x3a, 0x56, 0xd5, 0x80, 0x22, 0xef, 0x74, 0xd5, 0x23, 0x58, 0xb8, 0x94, 0x98, 0xbc, 0xef, 0x0c,
	0xf0, 0xb7, 0x61, 0xac, 0x9c, 0x90, 0x86, 0x98, 0xa5, 0x41, 0x18, 0xab, 0x77, 0x48, 0x83, 0xcf,
	0x46, 0x38, 0xf1, 0xfa, 0x22, 0x0b, 0xe7, 0x5c, 0x69, 0x6c, 0x7e, 0xf3, 0xf5, 0xab, 0x1e, 0x4d,
	0xfa, 0xc3, 0x4e, 0xcd, 0x0b, 0x07, 0xab, 0xfd, 0x2e, 0xf6, 0x56, 0x2e, 0xfc, 0x68, 0xb7, 0x42,
	0xc8, 0x4a, 0x2f, 0x8e, 0xbc, 0x95, 0x5e, 0xb8, 0x32, 0x4c, 0xa8, 0xbf, 0x2a, 0x8e, 0x42, 0x67,
	0x78, 0xba, 0x3a, 0xcd, 0x6f, 0x7b, 0x1d, 0x43, 0x3c, 0xde, 0xf8, 0x3b, 0x00, 0x00, 0xff, 0xff,
	0xf0, 0x7e, 0x61, 0x64, 0x0a, 0x14, 0x00, 0x00,
}
