// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: io/casperlabs/casper/consensus/consensus.proto

package consensus // import "github.com/hdac-io/casperlabs-ee-grpc-go-util/protobuf/io/casperlabs/casper/consensus"

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import state "github.com/hdac-io/casperlabs-ee-grpc-go-util/protobuf/io/casperlabs/casper/consensus/state"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type Block_MessageType int32

const (
	// Regular block (with deploys, multiple parents etc).
	Block_BLOCK Block_MessageType = 0
	// A message that doesn't have any deploys,
	// targets one block (no secondary parents),
	// and cannot be used as a parent (is a leaf in the DAG).
	Block_BALLOT Block_MessageType = 1
)

var Block_MessageType_name = map[int32]string{
	0: "BLOCK",
	1: "BALLOT",
}
var Block_MessageType_value = map[string]int32{
	"BLOCK":  0,
	"BALLOT": 1,
}

func (x Block_MessageType) String() string {
	return proto.EnumName(Block_MessageType_name, int32(x))
}
func (Block_MessageType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_consensus_a2847bf026c2e257, []int{5, 0}
}

// Highway specific role of a message.
type Block_MessageRole int32

const (
	Block_UNDEFINED Block_MessageRole = 0
	// Message from the round leader; a.k.a. lambda-message. Can be a block or ballot (during the voting period).
	Block_PROPOSAL Block_MessageRole = 1
	// Message in response to leader messages, with no other justification except the validator's own last message; a.k.a. lambda-response.
	Block_CONFIRMATION Block_MessageRole = 2
	// Message created during the round to form summits, a.k.a. omega-message.
	Block_WITNESS Block_MessageRole = 3
)

var Block_MessageRole_name = map[int32]string{
	0: "UNDEFINED",
	1: "PROPOSAL",
	2: "CONFIRMATION",
	3: "WITNESS",
}
var Block_MessageRole_value = map[string]int32{
	"UNDEFINED":    0,
	"PROPOSAL":     1,
	"CONFIRMATION": 2,
	"WITNESS":      3,
}

func (x Block_MessageRole) String() string {
	return proto.EnumName(Block_MessageRole_name, int32(x))
}
func (Block_MessageRole) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_consensus_a2847bf026c2e257, []int{5, 1}
}

// Signature over for example a deploy or a block. The location of the public key depends
// on the subject; for example if it's a block then the key is actually part of the data
// that needs to be signed over.
type Signature struct {
	// One of the supported algorithms: ed25519, secp256k1
	SigAlgorithm         string   `protobuf:"bytes,1,opt,name=sig_algorithm,json=sigAlgorithm,proto3" json:"sig_algorithm,omitempty"`
	Sig                  []byte   `protobuf:"bytes,2,opt,name=sig,proto3" json:"sig,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Signature) Reset()         { *m = Signature{} }
func (m *Signature) String() string { return proto.CompactTextString(m) }
func (*Signature) ProtoMessage()    {}
func (*Signature) Descriptor() ([]byte, []int) {
	return fileDescriptor_consensus_a2847bf026c2e257, []int{0}
}
func (m *Signature) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Signature.Unmarshal(m, b)
}
func (m *Signature) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Signature.Marshal(b, m, deterministic)
}
func (dst *Signature) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Signature.Merge(dst, src)
}
func (m *Signature) XXX_Size() int {
	return xxx_messageInfo_Signature.Size(m)
}
func (m *Signature) XXX_DiscardUnknown() {
	xxx_messageInfo_Signature.DiscardUnknown(m)
}

var xxx_messageInfo_Signature proto.InternalMessageInfo

func (m *Signature) GetSigAlgorithm() string {
	if m != nil {
		return m.SigAlgorithm
	}
	return ""
}

func (m *Signature) GetSig() []byte {
	if m != nil {
		return m.Sig
	}
	return nil
}

// A signature together with the corresponding public key that can be used to validate it
// for situations where the key is not part of the data being signed, which is usually the
// case where multiple signatures are required.
type Approval struct {
	ApproverPublicKey    []byte     `protobuf:"bytes,1,opt,name=approver_public_key,json=approverPublicKey,proto3" json:"approver_public_key,omitempty"`
	Signature            *Signature `protobuf:"bytes,2,opt,name=signature" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Approval) Reset()         { *m = Approval{} }
func (m *Approval) String() string { return proto.CompactTextString(m) }
func (*Approval) ProtoMessage()    {}
func (*Approval) Descriptor() ([]byte, []int) {
	return fileDescriptor_consensus_a2847bf026c2e257, []int{1}
}
func (m *Approval) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Approval.Unmarshal(m, b)
}
func (m *Approval) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Approval.Marshal(b, m, deterministic)
}
func (dst *Approval) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Approval.Merge(dst, src)
}
func (m *Approval) XXX_Size() int {
	return xxx_messageInfo_Approval.Size(m)
}
func (m *Approval) XXX_DiscardUnknown() {
	xxx_messageInfo_Approval.DiscardUnknown(m)
}

var xxx_messageInfo_Approval proto.InternalMessageInfo

func (m *Approval) GetApproverPublicKey() []byte {
	if m != nil {
		return m.ApproverPublicKey
	}
	return nil
}

func (m *Approval) GetSignature() *Signature {
	if m != nil {
		return m.Signature
	}
	return nil
}

// A smart contract invocation, singed by the account that sent it.
type Deploy struct {
	// blake2b256 hash of the `header`.
	DeployHash []byte         `protobuf:"bytes,1,opt,name=deploy_hash,json=deployHash,proto3" json:"deploy_hash,omitempty"`
	Header     *Deploy_Header `protobuf:"bytes,2,opt,name=header" json:"header,omitempty"`
	Body       *Deploy_Body   `protobuf:"bytes,3,opt,name=body" json:"body,omitempty"`
	// Signatures over `deploy_hash` with either the `account_public_key`, or some other keys in case of
	// multi-sig wallets and account recovery (when the private key corresponding to `account_public_key`
	// is lost.)
	Approvals            []*Approval `protobuf:"bytes,4,rep,name=approvals" json:"approvals,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Deploy) Reset()         { *m = Deploy{} }
func (m *Deploy) String() string { return proto.CompactTextString(m) }
func (*Deploy) ProtoMessage()    {}
func (*Deploy) Descriptor() ([]byte, []int) {
	return fileDescriptor_consensus_a2847bf026c2e257, []int{2}
}
func (m *Deploy) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Deploy.Unmarshal(m, b)
}
func (m *Deploy) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Deploy.Marshal(b, m, deterministic)
}
func (dst *Deploy) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Deploy.Merge(dst, src)
}
func (m *Deploy) XXX_Size() int {
	return xxx_messageInfo_Deploy.Size(m)
}
func (m *Deploy) XXX_DiscardUnknown() {
	xxx_messageInfo_Deploy.DiscardUnknown(m)
}

var xxx_messageInfo_Deploy proto.InternalMessageInfo

func (m *Deploy) GetDeployHash() []byte {
	if m != nil {
		return m.DeployHash
	}
	return nil
}

func (m *Deploy) GetHeader() *Deploy_Header {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *Deploy) GetBody() *Deploy_Body {
	if m != nil {
		return m.Body
	}
	return nil
}

func (m *Deploy) GetApprovals() []*Approval {
	if m != nil {
		return m.Approvals
	}
	return nil
}

type Deploy_Header struct {
	// Identifying the Account is the key used to sign the Deploy.
	AccountPublicKey []byte `protobuf:"bytes,1,opt,name=account_public_key,json=accountPublicKey,proto3" json:"account_public_key,omitempty"`
	// Current time milliseconds.
	Timestamp uint64 `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Conversion rate between the cost of Wasm opcodes and the motes sent by the `payment_code`.
	GasPrice uint64 `protobuf:"varint,4,opt,name=gas_price,json=gasPrice,proto3" json:"gas_price,omitempty"`
	// Hash of the body structure as a whole.
	BodyHash []byte `protobuf:"bytes,5,opt,name=body_hash,json=bodyHash,proto3" json:"body_hash,omitempty"`
	// Time to live of the deploy, in milliseconds. A deploy can only be
	// included in a block between Header.timestamp and
	// Header.timestamp + Header.ttl_millis. A value of 0 is interpreted as
	// 'not present' and a default value will be assigned instead.
	TtlMillis uint32 `protobuf:"varint,6,opt,name=ttl_millis,json=ttlMillis,proto3" json:"ttl_millis,omitempty"`
	// List of `Deploy.deploy_hash`s  that must be executed in past blocks
	// before this deploy can be executed.
	Dependencies [][]byte `protobuf:"bytes,7,rep,name=dependencies" json:"dependencies,omitempty"`
	// If present, the deploy can only be included in a block on the right chain.
	// This can be used to preotect against accidental or malicious cross chain
	// deploys, in case the same account exists on multiple networks.
	ChainName            string   `protobuf:"bytes,8,opt,name=chain_name,json=chainName,proto3" json:"chain_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Deploy_Header) Reset()         { *m = Deploy_Header{} }
func (m *Deploy_Header) String() string { return proto.CompactTextString(m) }
func (*Deploy_Header) ProtoMessage()    {}
func (*Deploy_Header) Descriptor() ([]byte, []int) {
	return fileDescriptor_consensus_a2847bf026c2e257, []int{2, 0}
}
func (m *Deploy_Header) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Deploy_Header.Unmarshal(m, b)
}
func (m *Deploy_Header) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Deploy_Header.Marshal(b, m, deterministic)
}
func (dst *Deploy_Header) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Deploy_Header.Merge(dst, src)
}
func (m *Deploy_Header) XXX_Size() int {
	return xxx_messageInfo_Deploy_Header.Size(m)
}
func (m *Deploy_Header) XXX_DiscardUnknown() {
	xxx_messageInfo_Deploy_Header.DiscardUnknown(m)
}

var xxx_messageInfo_Deploy_Header proto.InternalMessageInfo

func (m *Deploy_Header) GetAccountPublicKey() []byte {
	if m != nil {
		return m.AccountPublicKey
	}
	return nil
}

func (m *Deploy_Header) GetTimestamp() uint64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Deploy_Header) GetGasPrice() uint64 {
	if m != nil {
		return m.GasPrice
	}
	return 0
}

func (m *Deploy_Header) GetBodyHash() []byte {
	if m != nil {
		return m.BodyHash
	}
	return nil
}

func (m *Deploy_Header) GetTtlMillis() uint32 {
	if m != nil {
		return m.TtlMillis
	}
	return 0
}

func (m *Deploy_Header) GetDependencies() [][]byte {
	if m != nil {
		return m.Dependencies
	}
	return nil
}

func (m *Deploy_Header) GetChainName() string {
	if m != nil {
		return m.ChainName
	}
	return ""
}

type Deploy_Body struct {
	// Wasm code of the smart contract to be executed.
	Session *Deploy_Code `protobuf:"bytes,1,opt,name=session" json:"session,omitempty"`
	// Wasm code that transfers some motes to the validators as payment in exchange to run the Deploy.
	// Note: the word "mote" means "a tiny piece of a substance". Here we are referring to the smallest,
	// indivisible unit of the CL token. This is the equivalent of a Satoshi on Bitcoin or a Wei on Ethereum.
	Payment              *Deploy_Code `protobuf:"bytes,2,opt,name=payment" json:"payment,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Deploy_Body) Reset()         { *m = Deploy_Body{} }
func (m *Deploy_Body) String() string { return proto.CompactTextString(m) }
func (*Deploy_Body) ProtoMessage()    {}
func (*Deploy_Body) Descriptor() ([]byte, []int) {
	return fileDescriptor_consensus_a2847bf026c2e257, []int{2, 1}
}
func (m *Deploy_Body) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Deploy_Body.Unmarshal(m, b)
}
func (m *Deploy_Body) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Deploy_Body.Marshal(b, m, deterministic)
}
func (dst *Deploy_Body) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Deploy_Body.Merge(dst, src)
}
func (m *Deploy_Body) XXX_Size() int {
	return xxx_messageInfo_Deploy_Body.Size(m)
}
func (m *Deploy_Body) XXX_DiscardUnknown() {
	xxx_messageInfo_Deploy_Body.DiscardUnknown(m)
}

var xxx_messageInfo_Deploy_Body proto.InternalMessageInfo

func (m *Deploy_Body) GetSession() *Deploy_Code {
	if m != nil {
		return m.Session
	}
	return nil
}

func (m *Deploy_Body) GetPayment() *Deploy_Code {
	if m != nil {
		return m.Payment
	}
	return nil
}

// Code (either session or payment) to be deployed to the platform.
// Includes both binary instructions (wasm) and optionally, arguments
// to those instructions encoded via our ABI
type Deploy_Code struct {
	// Types that are valid to be assigned to Contract:
	//	*Deploy_Code_Wasm
	//	*Deploy_Code_Hash
	//	*Deploy_Code_Name
	//	*Deploy_Code_Uref
	Contract isDeploy_Code_Contract `protobuf_oneof:"contract"`
	// Keyword arguments. Note that while the execution engine works with the original
	// positional argument passing style, the order of the arguments matters.
	Args                 []*Deploy_Arg `protobuf:"bytes,6,rep,name=args" json:"args,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Deploy_Code) Reset()         { *m = Deploy_Code{} }
func (m *Deploy_Code) String() string { return proto.CompactTextString(m) }
func (*Deploy_Code) ProtoMessage()    {}
func (*Deploy_Code) Descriptor() ([]byte, []int) {
	return fileDescriptor_consensus_a2847bf026c2e257, []int{2, 2}
}
func (m *Deploy_Code) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Deploy_Code.Unmarshal(m, b)
}
func (m *Deploy_Code) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Deploy_Code.Marshal(b, m, deterministic)
}
func (dst *Deploy_Code) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Deploy_Code.Merge(dst, src)
}
func (m *Deploy_Code) XXX_Size() int {
	return xxx_messageInfo_Deploy_Code.Size(m)
}
func (m *Deploy_Code) XXX_DiscardUnknown() {
	xxx_messageInfo_Deploy_Code.DiscardUnknown(m)
}

var xxx_messageInfo_Deploy_Code proto.InternalMessageInfo

type isDeploy_Code_Contract interface {
	isDeploy_Code_Contract()
}

type Deploy_Code_Wasm struct {
	Wasm []byte `protobuf:"bytes,1,opt,name=wasm,proto3,oneof"`
}
type Deploy_Code_Hash struct {
	Hash []byte `protobuf:"bytes,3,opt,name=hash,proto3,oneof"`
}
type Deploy_Code_Name struct {
	Name string `protobuf:"bytes,4,opt,name=name,proto3,oneof"`
}
type Deploy_Code_Uref struct {
	Uref []byte `protobuf:"bytes,5,opt,name=uref,proto3,oneof"`
}

func (*Deploy_Code_Wasm) isDeploy_Code_Contract() {}
func (*Deploy_Code_Hash) isDeploy_Code_Contract() {}
func (*Deploy_Code_Name) isDeploy_Code_Contract() {}
func (*Deploy_Code_Uref) isDeploy_Code_Contract() {}

func (m *Deploy_Code) GetContract() isDeploy_Code_Contract {
	if m != nil {
		return m.Contract
	}
	return nil
}

func (m *Deploy_Code) GetWasm() []byte {
	if x, ok := m.GetContract().(*Deploy_Code_Wasm); ok {
		return x.Wasm
	}
	return nil
}

func (m *Deploy_Code) GetHash() []byte {
	if x, ok := m.GetContract().(*Deploy_Code_Hash); ok {
		return x.Hash
	}
	return nil
}

func (m *Deploy_Code) GetName() string {
	if x, ok := m.GetContract().(*Deploy_Code_Name); ok {
		return x.Name
	}
	return ""
}

func (m *Deploy_Code) GetUref() []byte {
	if x, ok := m.GetContract().(*Deploy_Code_Uref); ok {
		return x.Uref
	}
	return nil
}

func (m *Deploy_Code) GetArgs() []*Deploy_Arg {
	if m != nil {
		return m.Args
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Deploy_Code) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Deploy_Code_OneofMarshaler, _Deploy_Code_OneofUnmarshaler, _Deploy_Code_OneofSizer, []interface{}{
		(*Deploy_Code_Wasm)(nil),
		(*Deploy_Code_Hash)(nil),
		(*Deploy_Code_Name)(nil),
		(*Deploy_Code_Uref)(nil),
	}
}

func _Deploy_Code_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Deploy_Code)
	// contract
	switch x := m.Contract.(type) {
	case *Deploy_Code_Wasm:
		_ = b.EncodeVarint(1<<3 | proto.WireBytes)
		_ = b.EncodeRawBytes(x.Wasm)
	case *Deploy_Code_Hash:
		_ = b.EncodeVarint(3<<3 | proto.WireBytes)
		_ = b.EncodeRawBytes(x.Hash)
	case *Deploy_Code_Name:
		_ = b.EncodeVarint(4<<3 | proto.WireBytes)
		_ = b.EncodeStringBytes(x.Name)
	case *Deploy_Code_Uref:
		_ = b.EncodeVarint(5<<3 | proto.WireBytes)
		_ = b.EncodeRawBytes(x.Uref)
	case nil:
	default:
		return fmt.Errorf("Deploy_Code.Contract has unexpected type %T", x)
	}
	return nil
}

func _Deploy_Code_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Deploy_Code)
	switch tag {
	case 1: // contract.wasm
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeRawBytes(true)
		m.Contract = &Deploy_Code_Wasm{x}
		return true, err
	case 3: // contract.hash
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeRawBytes(true)
		m.Contract = &Deploy_Code_Hash{x}
		return true, err
	case 4: // contract.name
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.Contract = &Deploy_Code_Name{x}
		return true, err
	case 5: // contract.uref
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeRawBytes(true)
		m.Contract = &Deploy_Code_Uref{x}
		return true, err
	default:
		return false, nil
	}
}

func _Deploy_Code_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Deploy_Code)
	// contract
	switch x := m.Contract.(type) {
	case *Deploy_Code_Wasm:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(len(x.Wasm)))
		n += len(x.Wasm)
	case *Deploy_Code_Hash:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(len(x.Hash)))
		n += len(x.Hash)
	case *Deploy_Code_Name:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(len(x.Name)))
		n += len(x.Name)
	case *Deploy_Code_Uref:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(len(x.Uref)))
		n += len(x.Uref)
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type Deploy_Arg struct {
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Note that until the EE doesn't support kwargs directly, missing an Empty values are
	// not allowed because they would be ambiguous.
	Value                *state.CLValueInstance `protobuf:"bytes,3,opt,name=value" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *Deploy_Arg) Reset()         { *m = Deploy_Arg{} }
func (m *Deploy_Arg) String() string { return proto.CompactTextString(m) }
func (*Deploy_Arg) ProtoMessage()    {}
func (*Deploy_Arg) Descriptor() ([]byte, []int) {
	return fileDescriptor_consensus_a2847bf026c2e257, []int{2, 3}
}
func (m *Deploy_Arg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Deploy_Arg.Unmarshal(m, b)
}
func (m *Deploy_Arg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Deploy_Arg.Marshal(b, m, deterministic)
}
func (dst *Deploy_Arg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Deploy_Arg.Merge(dst, src)
}
func (m *Deploy_Arg) XXX_Size() int {
	return xxx_messageInfo_Deploy_Arg.Size(m)
}
func (m *Deploy_Arg) XXX_DiscardUnknown() {
	xxx_messageInfo_Deploy_Arg.DiscardUnknown(m)
}

var xxx_messageInfo_Deploy_Arg proto.InternalMessageInfo

func (m *Deploy_Arg) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Deploy_Arg) GetValue() *state.CLValueInstance {
	if m != nil {
		return m.Value
	}
	return nil
}

// Old definition of Arg, still kept around to support old JSON format.
// TODO: delete this when there are no more usages of the old JSON format
type Deploy_LegacyArg struct {
	Name                 string                  `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value                *Deploy_LegacyArg_Value `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *Deploy_LegacyArg) Reset()         { *m = Deploy_LegacyArg{} }
func (m *Deploy_LegacyArg) String() string { return proto.CompactTextString(m) }
func (*Deploy_LegacyArg) ProtoMessage()    {}
func (*Deploy_LegacyArg) Descriptor() ([]byte, []int) {
	return fileDescriptor_consensus_a2847bf026c2e257, []int{2, 4}
}
func (m *Deploy_LegacyArg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Deploy_LegacyArg.Unmarshal(m, b)
}
func (m *Deploy_LegacyArg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Deploy_LegacyArg.Marshal(b, m, deterministic)
}
func (dst *Deploy_LegacyArg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Deploy_LegacyArg.Merge(dst, src)
}
func (m *Deploy_LegacyArg) XXX_Size() int {
	return xxx_messageInfo_Deploy_LegacyArg.Size(m)
}
func (m *Deploy_LegacyArg) XXX_DiscardUnknown() {
	xxx_messageInfo_Deploy_LegacyArg.DiscardUnknown(m)
}

var xxx_messageInfo_Deploy_LegacyArg proto.InternalMessageInfo

func (m *Deploy_LegacyArg) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Deploy_LegacyArg) GetValue() *Deploy_LegacyArg_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

type Deploy_LegacyArg_Value struct {
	// Types that are valid to be assigned to Value:
	//	*Deploy_LegacyArg_Value_OptionalValue
	//	*Deploy_LegacyArg_Value_BytesValue
	//	*Deploy_LegacyArg_Value_IntValue
	//	*Deploy_LegacyArg_Value_IntList
	//	*Deploy_LegacyArg_Value_StringValue
	//	*Deploy_LegacyArg_Value_StringList
	//	*Deploy_LegacyArg_Value_LongValue
	//	*Deploy_LegacyArg_Value_BigInt
	//	*Deploy_LegacyArg_Value_Key
	Value                isDeploy_LegacyArg_Value_Value `protobuf_oneof:"value"`
	XXX_NoUnkeyedLiteral struct{}                       `json:"-"`
	XXX_unrecognized     []byte                         `json:"-"`
	XXX_sizecache        int32                          `json:"-"`
}

func (m *Deploy_LegacyArg_Value) Reset()         { *m = Deploy_LegacyArg_Value{} }
func (m *Deploy_LegacyArg_Value) String() string { return proto.CompactTextString(m) }
func (*Deploy_LegacyArg_Value) ProtoMessage()    {}
func (*Deploy_LegacyArg_Value) Descriptor() ([]byte, []int) {
	return fileDescriptor_consensus_a2847bf026c2e257, []int{2, 4, 0}
}
func (m *Deploy_LegacyArg_Value) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Deploy_LegacyArg_Value.Unmarshal(m, b)
}
func (m *Deploy_LegacyArg_Value) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Deploy_LegacyArg_Value.Marshal(b, m, deterministic)
}
func (dst *Deploy_LegacyArg_Value) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Deploy_LegacyArg_Value.Merge(dst, src)
}
func (m *Deploy_LegacyArg_Value) XXX_Size() int {
	return xxx_messageInfo_Deploy_LegacyArg_Value.Size(m)
}
func (m *Deploy_LegacyArg_Value) XXX_DiscardUnknown() {
	xxx_messageInfo_Deploy_LegacyArg_Value.DiscardUnknown(m)
}

var xxx_messageInfo_Deploy_LegacyArg_Value proto.InternalMessageInfo

type isDeploy_LegacyArg_Value_Value interface {
	isDeploy_LegacyArg_Value_Value()
}

type Deploy_LegacyArg_Value_OptionalValue struct {
	OptionalValue *Deploy_LegacyArg_Value `protobuf:"bytes,1,opt,name=optional_value,json=optionalValue,oneof"`
}
type Deploy_LegacyArg_Value_BytesValue struct {
	BytesValue []byte `protobuf:"bytes,2,opt,name=bytes_value,json=bytesValue,proto3,oneof"`
}
type Deploy_LegacyArg_Value_IntValue struct {
	IntValue int32 `protobuf:"varint,3,opt,name=int_value,json=intValue,proto3,oneof"`
}
type Deploy_LegacyArg_Value_IntList struct {
	IntList *state.IntList `protobuf:"bytes,4,opt,name=int_list,json=intList,oneof"`
}
type Deploy_LegacyArg_Value_StringValue struct {
	StringValue string `protobuf:"bytes,5,opt,name=string_value,json=stringValue,proto3,oneof"`
}
type Deploy_LegacyArg_Value_StringList struct {
	StringList *state.StringList `protobuf:"bytes,6,opt,name=string_list,json=stringList,oneof"`
}
type Deploy_LegacyArg_Value_LongValue struct {
	LongValue int64 `protobuf:"varint,7,opt,name=long_value,json=longValue,proto3,oneof"`
}
type Deploy_LegacyArg_Value_BigInt struct {
	BigInt *state.BigInt `protobuf:"bytes,8,opt,name=big_int,json=bigInt,oneof"`
}
type Deploy_LegacyArg_Value_Key struct {
	Key *state.Key `protobuf:"bytes,9,opt,name=key,oneof"`
}

func (*Deploy_LegacyArg_Value_OptionalValue) isDeploy_LegacyArg_Value_Value() {}
func (*Deploy_LegacyArg_Value_BytesValue) isDeploy_LegacyArg_Value_Value()    {}
func (*Deploy_LegacyArg_Value_IntValue) isDeploy_LegacyArg_Value_Value()      {}
func (*Deploy_LegacyArg_Value_IntList) isDeploy_LegacyArg_Value_Value()       {}
func (*Deploy_LegacyArg_Value_StringValue) isDeploy_LegacyArg_Value_Value()   {}
func (*Deploy_LegacyArg_Value_StringList) isDeploy_LegacyArg_Value_Value()    {}
func (*Deploy_LegacyArg_Value_LongValue) isDeploy_LegacyArg_Value_Value()     {}
func (*Deploy_LegacyArg_Value_BigInt) isDeploy_LegacyArg_Value_Value()        {}
func (*Deploy_LegacyArg_Value_Key) isDeploy_LegacyArg_Value_Value()           {}

func (m *Deploy_LegacyArg_Value) GetValue() isDeploy_LegacyArg_Value_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *Deploy_LegacyArg_Value) GetOptionalValue() *Deploy_LegacyArg_Value {
	if x, ok := m.GetValue().(*Deploy_LegacyArg_Value_OptionalValue); ok {
		return x.OptionalValue
	}
	return nil
}

func (m *Deploy_LegacyArg_Value) GetBytesValue() []byte {
	if x, ok := m.GetValue().(*Deploy_LegacyArg_Value_BytesValue); ok {
		return x.BytesValue
	}
	return nil
}

func (m *Deploy_LegacyArg_Value) GetIntValue() int32 {
	if x, ok := m.GetValue().(*Deploy_LegacyArg_Value_IntValue); ok {
		return x.IntValue
	}
	return 0
}

func (m *Deploy_LegacyArg_Value) GetIntList() *state.IntList {
	if x, ok := m.GetValue().(*Deploy_LegacyArg_Value_IntList); ok {
		return x.IntList
	}
	return nil
}

func (m *Deploy_LegacyArg_Value) GetStringValue() string {
	if x, ok := m.GetValue().(*Deploy_LegacyArg_Value_StringValue); ok {
		return x.StringValue
	}
	return ""
}

func (m *Deploy_LegacyArg_Value) GetStringList() *state.StringList {
	if x, ok := m.GetValue().(*Deploy_LegacyArg_Value_StringList); ok {
		return x.StringList
	}
	return nil
}

func (m *Deploy_LegacyArg_Value) GetLongValue() int64 {
	if x, ok := m.GetValue().(*Deploy_LegacyArg_Value_LongValue); ok {
		return x.LongValue
	}
	return 0
}

func (m *Deploy_LegacyArg_Value) GetBigInt() *state.BigInt {
	if x, ok := m.GetValue().(*Deploy_LegacyArg_Value_BigInt); ok {
		return x.BigInt
	}
	return nil
}

func (m *Deploy_LegacyArg_Value) GetKey() *state.Key {
	if x, ok := m.GetValue().(*Deploy_LegacyArg_Value_Key); ok {
		return x.Key
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Deploy_LegacyArg_Value) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Deploy_LegacyArg_Value_OneofMarshaler, _Deploy_LegacyArg_Value_OneofUnmarshaler, _Deploy_LegacyArg_Value_OneofSizer, []interface{}{
		(*Deploy_LegacyArg_Value_OptionalValue)(nil),
		(*Deploy_LegacyArg_Value_BytesValue)(nil),
		(*Deploy_LegacyArg_Value_IntValue)(nil),
		(*Deploy_LegacyArg_Value_IntList)(nil),
		(*Deploy_LegacyArg_Value_StringValue)(nil),
		(*Deploy_LegacyArg_Value_StringList)(nil),
		(*Deploy_LegacyArg_Value_LongValue)(nil),
		(*Deploy_LegacyArg_Value_BigInt)(nil),
		(*Deploy_LegacyArg_Value_Key)(nil),
	}
}

func _Deploy_LegacyArg_Value_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Deploy_LegacyArg_Value)
	// value
	switch x := m.Value.(type) {
	case *Deploy_LegacyArg_Value_OptionalValue:
		_ = b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.OptionalValue); err != nil {
			return err
		}
	case *Deploy_LegacyArg_Value_BytesValue:
		_ = b.EncodeVarint(2<<3 | proto.WireBytes)
		_ = b.EncodeRawBytes(x.BytesValue)
	case *Deploy_LegacyArg_Value_IntValue:
		_ = b.EncodeVarint(3<<3 | proto.WireVarint)
		_ = b.EncodeVarint(uint64(x.IntValue))
	case *Deploy_LegacyArg_Value_IntList:
		_ = b.EncodeVarint(4<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.IntList); err != nil {
			return err
		}
	case *Deploy_LegacyArg_Value_StringValue:
		_ = b.EncodeVarint(5<<3 | proto.WireBytes)
		_ = b.EncodeStringBytes(x.StringValue)
	case *Deploy_LegacyArg_Value_StringList:
		_ = b.EncodeVarint(6<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.StringList); err != nil {
			return err
		}
	case *Deploy_LegacyArg_Value_LongValue:
		_ = b.EncodeVarint(7<<3 | proto.WireVarint)
		_ = b.EncodeVarint(uint64(x.LongValue))
	case *Deploy_LegacyArg_Value_BigInt:
		_ = b.EncodeVarint(8<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.BigInt); err != nil {
			return err
		}
	case *Deploy_LegacyArg_Value_Key:
		_ = b.EncodeVarint(9<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Key); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("Deploy_LegacyArg_Value.Value has unexpected type %T", x)
	}
	return nil
}

func _Deploy_LegacyArg_Value_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Deploy_LegacyArg_Value)
	switch tag {
	case 1: // value.optional_value
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Deploy_LegacyArg_Value)
		err := b.DecodeMessage(msg)
		m.Value = &Deploy_LegacyArg_Value_OptionalValue{msg}
		return true, err
	case 2: // value.bytes_value
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeRawBytes(true)
		m.Value = &Deploy_LegacyArg_Value_BytesValue{x}
		return true, err
	case 3: // value.int_value
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.Value = &Deploy_LegacyArg_Value_IntValue{int32(x)}
		return true, err
	case 4: // value.int_list
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(state.IntList)
		err := b.DecodeMessage(msg)
		m.Value = &Deploy_LegacyArg_Value_IntList{msg}
		return true, err
	case 5: // value.string_value
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.Value = &Deploy_LegacyArg_Value_StringValue{x}
		return true, err
	case 6: // value.string_list
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(state.StringList)
		err := b.DecodeMessage(msg)
		m.Value = &Deploy_LegacyArg_Value_StringList{msg}
		return true, err
	case 7: // value.long_value
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.Value = &Deploy_LegacyArg_Value_LongValue{int64(x)}
		return true, err
	case 8: // value.big_int
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(state.BigInt)
		err := b.DecodeMessage(msg)
		m.Value = &Deploy_LegacyArg_Value_BigInt{msg}
		return true, err
	case 9: // value.key
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(state.Key)
		err := b.DecodeMessage(msg)
		m.Value = &Deploy_LegacyArg_Value_Key{msg}
		return true, err
	default:
		return false, nil
	}
}

func _Deploy_LegacyArg_Value_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Deploy_LegacyArg_Value)
	// value
	switch x := m.Value.(type) {
	case *Deploy_LegacyArg_Value_OptionalValue:
		s := proto.Size(x.OptionalValue)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Deploy_LegacyArg_Value_BytesValue:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(len(x.BytesValue)))
		n += len(x.BytesValue)
	case *Deploy_LegacyArg_Value_IntValue:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(x.IntValue))
	case *Deploy_LegacyArg_Value_IntList:
		s := proto.Size(x.IntList)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Deploy_LegacyArg_Value_StringValue:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(len(x.StringValue)))
		n += len(x.StringValue)
	case *Deploy_LegacyArg_Value_StringList:
		s := proto.Size(x.StringList)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Deploy_LegacyArg_Value_LongValue:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(x.LongValue))
	case *Deploy_LegacyArg_Value_BigInt:
		s := proto.Size(x.BigInt)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Deploy_LegacyArg_Value_Key:
		s := proto.Size(x.Key)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

// Limited deploy information for gossiping.
type DeploySummary struct {
	// blake2b256 hash of the `header`.
	DeployHash []byte         `protobuf:"bytes,1,opt,name=deploy_hash,json=deployHash,proto3" json:"deploy_hash,omitempty"`
	Header     *Deploy_Header `protobuf:"bytes,2,opt,name=header" json:"header,omitempty"`
	// Signatures over `deploy_hash` with either the `account_public_key`, or some other keys in case of
	// multi-sig wallets and account recovery (when the private key corresponding to `account_public_key`
	// is lost.)
	Approvals            []*Approval `protobuf:"bytes,3,rep,name=approvals" json:"approvals,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *DeploySummary) Reset()         { *m = DeploySummary{} }
func (m *DeploySummary) String() string { return proto.CompactTextString(m) }
func (*DeploySummary) ProtoMessage()    {}
func (*DeploySummary) Descriptor() ([]byte, []int) {
	return fileDescriptor_consensus_a2847bf026c2e257, []int{3}
}
func (m *DeploySummary) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeploySummary.Unmarshal(m, b)
}
func (m *DeploySummary) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeploySummary.Marshal(b, m, deterministic)
}
func (dst *DeploySummary) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeploySummary.Merge(dst, src)
}
func (m *DeploySummary) XXX_Size() int {
	return xxx_messageInfo_DeploySummary.Size(m)
}
func (m *DeploySummary) XXX_DiscardUnknown() {
	xxx_messageInfo_DeploySummary.DiscardUnknown(m)
}

var xxx_messageInfo_DeploySummary proto.InternalMessageInfo

func (m *DeploySummary) GetDeployHash() []byte {
	if m != nil {
		return m.DeployHash
	}
	return nil
}

func (m *DeploySummary) GetHeader() *Deploy_Header {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *DeploySummary) GetApprovals() []*Approval {
	if m != nil {
		return m.Approvals
	}
	return nil
}

// Limited block information for gossiping.
type BlockSummary struct {
	// blake2b256 hash of the `header`.
	BlockHash []byte        `protobuf:"bytes,1,opt,name=block_hash,json=blockHash,proto3" json:"block_hash,omitempty"`
	Header    *Block_Header `protobuf:"bytes,2,opt,name=header" json:"header,omitempty"`
	// Signature over `block_hash` using `validator_public_key`.
	Signature            *Signature `protobuf:"bytes,3,opt,name=signature" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *BlockSummary) Reset()         { *m = BlockSummary{} }
func (m *BlockSummary) String() string { return proto.CompactTextString(m) }
func (*BlockSummary) ProtoMessage()    {}
func (*BlockSummary) Descriptor() ([]byte, []int) {
	return fileDescriptor_consensus_a2847bf026c2e257, []int{4}
}
func (m *BlockSummary) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockSummary.Unmarshal(m, b)
}
func (m *BlockSummary) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockSummary.Marshal(b, m, deterministic)
}
func (dst *BlockSummary) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockSummary.Merge(dst, src)
}
func (m *BlockSummary) XXX_Size() int {
	return xxx_messageInfo_BlockSummary.Size(m)
}
func (m *BlockSummary) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockSummary.DiscardUnknown(m)
}

var xxx_messageInfo_BlockSummary proto.InternalMessageInfo

func (m *BlockSummary) GetBlockHash() []byte {
	if m != nil {
		return m.BlockHash
	}
	return nil
}

func (m *BlockSummary) GetHeader() *Block_Header {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *BlockSummary) GetSignature() *Signature {
	if m != nil {
		return m.Signature
	}
	return nil
}

// Full block information.
type Block struct {
	// blake2b256 hash of the `header`.
	BlockHash []byte        `protobuf:"bytes,1,opt,name=block_hash,json=blockHash,proto3" json:"block_hash,omitempty"`
	Header    *Block_Header `protobuf:"bytes,2,opt,name=header" json:"header,omitempty"`
	Body      *Block_Body   `protobuf:"bytes,3,opt,name=body" json:"body,omitempty"`
	// Signature over `block_hash`.
	Signature            *Signature `protobuf:"bytes,4,opt,name=signature" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Block) Reset()         { *m = Block{} }
func (m *Block) String() string { return proto.CompactTextString(m) }
func (*Block) ProtoMessage()    {}
func (*Block) Descriptor() ([]byte, []int) {
	return fileDescriptor_consensus_a2847bf026c2e257, []int{5}
}
func (m *Block) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Block.Unmarshal(m, b)
}
func (m *Block) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Block.Marshal(b, m, deterministic)
}
func (dst *Block) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Block.Merge(dst, src)
}
func (m *Block) XXX_Size() int {
	return xxx_messageInfo_Block.Size(m)
}
func (m *Block) XXX_DiscardUnknown() {
	xxx_messageInfo_Block.DiscardUnknown(m)
}

var xxx_messageInfo_Block proto.InternalMessageInfo

func (m *Block) GetBlockHash() []byte {
	if m != nil {
		return m.BlockHash
	}
	return nil
}

func (m *Block) GetHeader() *Block_Header {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *Block) GetBody() *Block_Body {
	if m != nil {
		return m.Body
	}
	return nil
}

func (m *Block) GetSignature() *Signature {
	if m != nil {
		return m.Signature
	}
	return nil
}

type Block_Header struct {
	ParentHashes   [][]byte               `protobuf:"bytes,1,rep,name=parent_hashes,json=parentHashes" json:"parent_hashes,omitempty"`
	Justifications []*Block_Justification `protobuf:"bytes,2,rep,name=justifications" json:"justifications,omitempty"`
	State          *Block_GlobalState     `protobuf:"bytes,3,opt,name=state" json:"state,omitempty"`
	// Hash of the body structure as a whole.
	BodyHash []byte `protobuf:"bytes,4,opt,name=body_hash,json=bodyHash,proto3" json:"body_hash,omitempty"`
	// Unix timestamp from when the block was created.
	Timestamp            uint64                 `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	ProtocolVersion      *state.ProtocolVersion `protobuf:"bytes,13,opt,name=protocol_version,json=protocolVersion" json:"protocol_version,omitempty"`
	DeployCount          uint32                 `protobuf:"varint,7,opt,name=deploy_count,json=deployCount,proto3" json:"deploy_count,omitempty"`
	ChainName            string                 `protobuf:"bytes,8,opt,name=chain_name,json=chainName,proto3" json:"chain_name,omitempty"`
	ValidatorBlockSeqNum uint32                 `protobuf:"varint,9,opt,name=validator_block_seq_num,json=validatorBlockSeqNum,proto3" json:"validator_block_seq_num,omitempty"`
	ValidatorPublicKey   []byte                 `protobuf:"bytes,10,opt,name=validator_public_key,json=validatorPublicKey,proto3" json:"validator_public_key,omitempty"`
	// The hash of the previous block (or ballot) from this validator.
	// It has to be stated even if it's part of the justifications directly,
	// and it must be part of the j-past-cone of the block, in case transitive
	// justifications are omitted. It must be the one corresponding to
	// validator_block_seq_num - 1.
	ValidatorPrevBlockHash []byte `protobuf:"bytes,14,opt,name=validator_prev_block_hash,json=validatorPrevBlockHash,proto3" json:"validator_prev_block_hash,omitempty"`
	// Distance from Genesis.
	// This is a rank based on the justifications of the message.
	JRank       uint64            `protobuf:"varint,11,opt,name=j_rank,json=jRank,proto3" json:"j_rank,omitempty"`
	MessageType Block_MessageType `protobuf:"varint,12,opt,name=message_type,json=messageType,proto3,enum=io.casperlabs.casper.consensus.Block_MessageType" json:"message_type,omitempty"`
	MessageRole Block_MessageRole `protobuf:"varint,19,opt,name=message_role,json=messageRole,proto3,enum=io.casperlabs.casper.consensus.Block_MessageRole" json:"message_role,omitempty"`
	// A block from where the fork choice is calculated.
	// Corresponds to the era the block belongs to.
	KeyBlockHash []byte `protobuf:"bytes,15,opt,name=key_block_hash,json=keyBlockHash,proto3" json:"key_block_hash,omitempty"`
	// The round ID (the idealistic protocol timestamp) to which the block belongs;
	// this will be slightly different from the timestamp, which is the wall clock time
	// of when the block was _actually_ created.
	RoundId uint64 `protobuf:"varint,16,opt,name=round_id,json=roundId,proto3" json:"round_id,omitempty"`
	// A random bit set by the creator of the block which is goes towards the leader seed
	// of the era. Only leader blocks (i.e. lambda messages) have to set it; should be
	// empty for ballots.
	MagicBit bool `protobuf:"varint,17,opt,name=magic_bit,json=magicBit,proto3" json:"magic_bit,omitempty"`
	// Block height.
	// Different from `j_rank` because it's incremented along main tree in the DAG, based on the parents.
	MainRank             uint64   `protobuf:"varint,18,opt,name=main_rank,json=mainRank,proto3" json:"main_rank,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Block_Header) Reset()         { *m = Block_Header{} }
func (m *Block_Header) String() string { return proto.CompactTextString(m) }
func (*Block_Header) ProtoMessage()    {}
func (*Block_Header) Descriptor() ([]byte, []int) {
	return fileDescriptor_consensus_a2847bf026c2e257, []int{5, 0}
}
func (m *Block_Header) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Block_Header.Unmarshal(m, b)
}
func (m *Block_Header) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Block_Header.Marshal(b, m, deterministic)
}
func (dst *Block_Header) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Block_Header.Merge(dst, src)
}
func (m *Block_Header) XXX_Size() int {
	return xxx_messageInfo_Block_Header.Size(m)
}
func (m *Block_Header) XXX_DiscardUnknown() {
	xxx_messageInfo_Block_Header.DiscardUnknown(m)
}

var xxx_messageInfo_Block_Header proto.InternalMessageInfo

func (m *Block_Header) GetParentHashes() [][]byte {
	if m != nil {
		return m.ParentHashes
	}
	return nil
}

func (m *Block_Header) GetJustifications() []*Block_Justification {
	if m != nil {
		return m.Justifications
	}
	return nil
}

func (m *Block_Header) GetState() *Block_GlobalState {
	if m != nil {
		return m.State
	}
	return nil
}

func (m *Block_Header) GetBodyHash() []byte {
	if m != nil {
		return m.BodyHash
	}
	return nil
}

func (m *Block_Header) GetTimestamp() uint64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Block_Header) GetProtocolVersion() *state.ProtocolVersion {
	if m != nil {
		return m.ProtocolVersion
	}
	return nil
}

func (m *Block_Header) GetDeployCount() uint32 {
	if m != nil {
		return m.DeployCount
	}
	return 0
}

func (m *Block_Header) GetChainName() string {
	if m != nil {
		return m.ChainName
	}
	return ""
}

func (m *Block_Header) GetValidatorBlockSeqNum() uint32 {
	if m != nil {
		return m.ValidatorBlockSeqNum
	}
	return 0
}

func (m *Block_Header) GetValidatorPublicKey() []byte {
	if m != nil {
		return m.ValidatorPublicKey
	}
	return nil
}

func (m *Block_Header) GetValidatorPrevBlockHash() []byte {
	if m != nil {
		return m.ValidatorPrevBlockHash
	}
	return nil
}

func (m *Block_Header) GetJRank() uint64 {
	if m != nil {
		return m.JRank
	}
	return 0
}

func (m *Block_Header) GetMessageType() Block_MessageType {
	if m != nil {
		return m.MessageType
	}
	return Block_BLOCK
}

func (m *Block_Header) GetMessageRole() Block_MessageRole {
	if m != nil {
		return m.MessageRole
	}
	return Block_UNDEFINED
}

func (m *Block_Header) GetKeyBlockHash() []byte {
	if m != nil {
		return m.KeyBlockHash
	}
	return nil
}

func (m *Block_Header) GetRoundId() uint64 {
	if m != nil {
		return m.RoundId
	}
	return 0
}

func (m *Block_Header) GetMagicBit() bool {
	if m != nil {
		return m.MagicBit
	}
	return false
}

func (m *Block_Header) GetMainRank() uint64 {
	if m != nil {
		return m.MainRank
	}
	return 0
}

type Block_Body struct {
	Deploys              []*Block_ProcessedDeploy `protobuf:"bytes,1,rep,name=deploys" json:"deploys,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *Block_Body) Reset()         { *m = Block_Body{} }
func (m *Block_Body) String() string { return proto.CompactTextString(m) }
func (*Block_Body) ProtoMessage()    {}
func (*Block_Body) Descriptor() ([]byte, []int) {
	return fileDescriptor_consensus_a2847bf026c2e257, []int{5, 1}
}
func (m *Block_Body) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Block_Body.Unmarshal(m, b)
}
func (m *Block_Body) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Block_Body.Marshal(b, m, deterministic)
}
func (dst *Block_Body) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Block_Body.Merge(dst, src)
}
func (m *Block_Body) XXX_Size() int {
	return xxx_messageInfo_Block_Body.Size(m)
}
func (m *Block_Body) XXX_DiscardUnknown() {
	xxx_messageInfo_Block_Body.DiscardUnknown(m)
}

var xxx_messageInfo_Block_Body proto.InternalMessageInfo

func (m *Block_Body) GetDeploys() []*Block_ProcessedDeploy {
	if m != nil {
		return m.Deploys
	}
	return nil
}

type Block_Justification struct {
	ValidatorPublicKey   []byte   `protobuf:"bytes,1,opt,name=validator_public_key,json=validatorPublicKey,proto3" json:"validator_public_key,omitempty"`
	LatestBlockHash      []byte   `protobuf:"bytes,2,opt,name=latest_block_hash,json=latestBlockHash,proto3" json:"latest_block_hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Block_Justification) Reset()         { *m = Block_Justification{} }
func (m *Block_Justification) String() string { return proto.CompactTextString(m) }
func (*Block_Justification) ProtoMessage()    {}
func (*Block_Justification) Descriptor() ([]byte, []int) {
	return fileDescriptor_consensus_a2847bf026c2e257, []int{5, 2}
}
func (m *Block_Justification) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Block_Justification.Unmarshal(m, b)
}
func (m *Block_Justification) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Block_Justification.Marshal(b, m, deterministic)
}
func (dst *Block_Justification) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Block_Justification.Merge(dst, src)
}
func (m *Block_Justification) XXX_Size() int {
	return xxx_messageInfo_Block_Justification.Size(m)
}
func (m *Block_Justification) XXX_DiscardUnknown() {
	xxx_messageInfo_Block_Justification.DiscardUnknown(m)
}

var xxx_messageInfo_Block_Justification proto.InternalMessageInfo

func (m *Block_Justification) GetValidatorPublicKey() []byte {
	if m != nil {
		return m.ValidatorPublicKey
	}
	return nil
}

func (m *Block_Justification) GetLatestBlockHash() []byte {
	if m != nil {
		return m.LatestBlockHash
	}
	return nil
}

type Block_ProcessedDeploy struct {
	Deploy       *Deploy `protobuf:"bytes,1,opt,name=deploy" json:"deploy,omitempty"`
	Cost         uint64  `protobuf:"varint,2,opt,name=cost,proto3" json:"cost,omitempty"`
	IsError      bool    `protobuf:"varint,3,opt,name=is_error,json=isError,proto3" json:"is_error,omitempty"`
	ErrorMessage string  `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	// A group this deploy will be executed in.
	// Deploys with the same `stage` value will be executed in parallel.
	Stage                uint32   `protobuf:"varint,5,opt,name=stage,proto3" json:"stage,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Block_ProcessedDeploy) Reset()         { *m = Block_ProcessedDeploy{} }
func (m *Block_ProcessedDeploy) String() string { return proto.CompactTextString(m) }
func (*Block_ProcessedDeploy) ProtoMessage()    {}
func (*Block_ProcessedDeploy) Descriptor() ([]byte, []int) {
	return fileDescriptor_consensus_a2847bf026c2e257, []int{5, 3}
}
func (m *Block_ProcessedDeploy) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Block_ProcessedDeploy.Unmarshal(m, b)
}
func (m *Block_ProcessedDeploy) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Block_ProcessedDeploy.Marshal(b, m, deterministic)
}
func (dst *Block_ProcessedDeploy) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Block_ProcessedDeploy.Merge(dst, src)
}
func (m *Block_ProcessedDeploy) XXX_Size() int {
	return xxx_messageInfo_Block_ProcessedDeploy.Size(m)
}
func (m *Block_ProcessedDeploy) XXX_DiscardUnknown() {
	xxx_messageInfo_Block_ProcessedDeploy.DiscardUnknown(m)
}

var xxx_messageInfo_Block_ProcessedDeploy proto.InternalMessageInfo

func (m *Block_ProcessedDeploy) GetDeploy() *Deploy {
	if m != nil {
		return m.Deploy
	}
	return nil
}

func (m *Block_ProcessedDeploy) GetCost() uint64 {
	if m != nil {
		return m.Cost
	}
	return 0
}

func (m *Block_ProcessedDeploy) GetIsError() bool {
	if m != nil {
		return m.IsError
	}
	return false
}

func (m *Block_ProcessedDeploy) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

func (m *Block_ProcessedDeploy) GetStage() uint32 {
	if m != nil {
		return m.Stage
	}
	return 0
}

type Block_GlobalState struct {
	// May not correspond to a particular block if there are multiple parents.
	PreStateHash  []byte `protobuf:"bytes,1,opt,name=pre_state_hash,json=preStateHash,proto3" json:"pre_state_hash,omitempty"`
	PostStateHash []byte `protobuf:"bytes,2,opt,name=post_state_hash,json=postStateHash,proto3" json:"post_state_hash,omitempty"`
	// Included in header so lightweight nodes can follow the consensus.
	Bonds                []*Bond  `protobuf:"bytes,3,rep,name=bonds" json:"bonds,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Block_GlobalState) Reset()         { *m = Block_GlobalState{} }
func (m *Block_GlobalState) String() string { return proto.CompactTextString(m) }
func (*Block_GlobalState) ProtoMessage()    {}
func (*Block_GlobalState) Descriptor() ([]byte, []int) {
	return fileDescriptor_consensus_a2847bf026c2e257, []int{5, 4}
}
func (m *Block_GlobalState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Block_GlobalState.Unmarshal(m, b)
}
func (m *Block_GlobalState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Block_GlobalState.Marshal(b, m, deterministic)
}
func (dst *Block_GlobalState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Block_GlobalState.Merge(dst, src)
}
func (m *Block_GlobalState) XXX_Size() int {
	return xxx_messageInfo_Block_GlobalState.Size(m)
}
func (m *Block_GlobalState) XXX_DiscardUnknown() {
	xxx_messageInfo_Block_GlobalState.DiscardUnknown(m)
}

var xxx_messageInfo_Block_GlobalState proto.InternalMessageInfo

func (m *Block_GlobalState) GetPreStateHash() []byte {
	if m != nil {
		return m.PreStateHash
	}
	return nil
}

func (m *Block_GlobalState) GetPostStateHash() []byte {
	if m != nil {
		return m.PostStateHash
	}
	return nil
}

func (m *Block_GlobalState) GetBonds() []*Bond {
	if m != nil {
		return m.Bonds
	}
	return nil
}

type Bond struct {
	ValidatorPublicKey   []byte        `protobuf:"bytes,1,opt,name=validator_public_key,json=validatorPublicKey,proto3" json:"validator_public_key,omitempty"`
	Stake                *state.BigInt `protobuf:"bytes,3,opt,name=stake" json:"stake,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Bond) Reset()         { *m = Bond{} }
func (m *Bond) String() string { return proto.CompactTextString(m) }
func (*Bond) ProtoMessage()    {}
func (*Bond) Descriptor() ([]byte, []int) {
	return fileDescriptor_consensus_a2847bf026c2e257, []int{6}
}
func (m *Bond) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Bond.Unmarshal(m, b)
}
func (m *Bond) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Bond.Marshal(b, m, deterministic)
}
func (dst *Bond) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Bond.Merge(dst, src)
}
func (m *Bond) XXX_Size() int {
	return xxx_messageInfo_Bond.Size(m)
}
func (m *Bond) XXX_DiscardUnknown() {
	xxx_messageInfo_Bond.DiscardUnknown(m)
}

var xxx_messageInfo_Bond proto.InternalMessageInfo

func (m *Bond) GetValidatorPublicKey() []byte {
	if m != nil {
		return m.ValidatorPublicKey
	}
	return nil
}

func (m *Bond) GetStake() *state.BigInt {
	if m != nil {
		return m.Stake
	}
	return nil
}

// To allow nodes in the beginning to verify that they are joining the right network,
// while there is no DAG to look at, they disseminate approvals for the Genesis candidate
// until it gathers enough support for individual nodes to pass their thresholds and
// transition to processing blocks and deploys.
// Nodes should persist this value to be able to retrieve it later even if in case all nodes are restarted.
type GenesisCandidate struct {
	// The hash of the Genesis block, which should reflect the effects of executing
	// the block that was compiled according to the published specification.
	// The Genesis block is special in that it is not signed by any one validator:
	// all the signatures are going to be missing, all the public key fields empty,
	// including those that would sign the deploys in the body.
	BlockHash []byte `protobuf:"bytes,1,opt,name=block_hash,json=blockHash,proto3" json:"block_hash,omitempty"`
	// Approvals from bonded validators with signatures over the `block_hash`.
	Approvals            []*Approval `protobuf:"bytes,2,rep,name=approvals" json:"approvals,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GenesisCandidate) Reset()         { *m = GenesisCandidate{} }
func (m *GenesisCandidate) String() string { return proto.CompactTextString(m) }
func (*GenesisCandidate) ProtoMessage()    {}
func (*GenesisCandidate) Descriptor() ([]byte, []int) {
	return fileDescriptor_consensus_a2847bf026c2e257, []int{7}
}
func (m *GenesisCandidate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenesisCandidate.Unmarshal(m, b)
}
func (m *GenesisCandidate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenesisCandidate.Marshal(b, m, deterministic)
}
func (dst *GenesisCandidate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisCandidate.Merge(dst, src)
}
func (m *GenesisCandidate) XXX_Size() int {
	return xxx_messageInfo_GenesisCandidate.Size(m)
}
func (m *GenesisCandidate) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisCandidate.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisCandidate proto.InternalMessageInfo

func (m *GenesisCandidate) GetBlockHash() []byte {
	if m != nil {
		return m.BlockHash
	}
	return nil
}

func (m *GenesisCandidate) GetApprovals() []*Approval {
	if m != nil {
		return m.Approvals
	}
	return nil
}

type Era struct {
	// Key block of the era, which is basically its identifier.
	KeyBlockHash []byte `protobuf:"bytes,1,opt,name=key_block_hash,json=keyBlockHash,proto3" json:"key_block_hash,omitempty"`
	// Identifier of the parent era.
	ParentKeyBlockHash []byte `protobuf:"bytes,2,opt,name=parent_key_block_hash,json=parentKeyBlockHash,proto3" json:"parent_key_block_hash,omitempty"`
	// Number of ticks since Unix epoch (in the protocol specific units) when the era starts.
	StartTick uint64 `protobuf:"varint,3,opt,name=start_tick,json=startTick,proto3" json:"start_tick,omitempty"`
	// Last round of the era (non-inclusive), after which the first block is the switch block.
	EndTick uint64 `protobuf:"varint,4,opt,name=end_tick,json=endTick,proto3" json:"end_tick,omitempty"`
	// The hash of the booking block which was reachable from the key block;
	// this is where the bonds are coming, included in the era for reference.
	BookingBlockHash []byte `protobuf:"bytes,5,opt,name=booking_block_hash,json=bookingBlockHash,proto3" json:"booking_block_hash,omitempty"`
	// The random seed compiled from the magic bits between the booking block and the key block.
	// 1. Concatenate all the magic bits into an array of bytes, padding on the right with 0s to make it divisble by 8.
	// 2. Concatenate the byte array to the parent leader seed.
	// 3. Let the leader_seed be the blake2b256 hash of the resulting array.
	// 4. Convert any uint64 tick to bytes in little-endian format.
	// 5. Concatentate the the bytes of the tick to the leader_seed and use the array as a seed to a SHA1PRNG generator.
	// 6. Generate a random double r between [0, 1) and seek the first validator in `bonds` where the total cumulative weight exceeds r * total.
	LeaderSeed []byte `protobuf:"bytes,6,opt,name=leader_seed,json=leaderSeed,proto3" json:"leader_seed,omitempty"`
	// Bonded validator weights from the booking block.
	Bonds                []*Bond  `protobuf:"bytes,7,rep,name=bonds" json:"bonds,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Era) Reset()         { *m = Era{} }
func (m *Era) String() string { return proto.CompactTextString(m) }
func (*Era) ProtoMessage()    {}
func (*Era) Descriptor() ([]byte, []int) {
	return fileDescriptor_consensus_a2847bf026c2e257, []int{8}
}
func (m *Era) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Era.Unmarshal(m, b)
}
func (m *Era) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Era.Marshal(b, m, deterministic)
}
func (dst *Era) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Era.Merge(dst, src)
}
func (m *Era) XXX_Size() int {
	return xxx_messageInfo_Era.Size(m)
}
func (m *Era) XXX_DiscardUnknown() {
	xxx_messageInfo_Era.DiscardUnknown(m)
}

var xxx_messageInfo_Era proto.InternalMessageInfo

func (m *Era) GetKeyBlockHash() []byte {
	if m != nil {
		return m.KeyBlockHash
	}
	return nil
}

func (m *Era) GetParentKeyBlockHash() []byte {
	if m != nil {
		return m.ParentKeyBlockHash
	}
	return nil
}

func (m *Era) GetStartTick() uint64 {
	if m != nil {
		return m.StartTick
	}
	return 0
}

func (m *Era) GetEndTick() uint64 {
	if m != nil {
		return m.EndTick
	}
	return 0
}

func (m *Era) GetBookingBlockHash() []byte {
	if m != nil {
		return m.BookingBlockHash
	}
	return nil
}

func (m *Era) GetLeaderSeed() []byte {
	if m != nil {
		return m.LeaderSeed
	}
	return nil
}

func (m *Era) GetBonds() []*Bond {
	if m != nil {
		return m.Bonds
	}
	return nil
}

func init() {
	proto.RegisterType((*Signature)(nil), "io.casperlabs.casper.consensus.Signature")
	proto.RegisterType((*Approval)(nil), "io.casperlabs.casper.consensus.Approval")
	proto.RegisterType((*Deploy)(nil), "io.casperlabs.casper.consensus.Deploy")
	proto.RegisterType((*Deploy_Header)(nil), "io.casperlabs.casper.consensus.Deploy.Header")
	proto.RegisterType((*Deploy_Body)(nil), "io.casperlabs.casper.consensus.Deploy.Body")
	proto.RegisterType((*Deploy_Code)(nil), "io.casperlabs.casper.consensus.Deploy.Code")
	proto.RegisterType((*Deploy_Arg)(nil), "io.casperlabs.casper.consensus.Deploy.Arg")
	proto.RegisterType((*Deploy_LegacyArg)(nil), "io.casperlabs.casper.consensus.Deploy.LegacyArg")
	proto.RegisterType((*Deploy_LegacyArg_Value)(nil), "io.casperlabs.casper.consensus.Deploy.LegacyArg.Value")
	proto.RegisterType((*DeploySummary)(nil), "io.casperlabs.casper.consensus.DeploySummary")
	proto.RegisterType((*BlockSummary)(nil), "io.casperlabs.casper.consensus.BlockSummary")
	proto.RegisterType((*Block)(nil), "io.casperlabs.casper.consensus.Block")
	proto.RegisterType((*Block_Header)(nil), "io.casperlabs.casper.consensus.Block.Header")
	proto.RegisterType((*Block_Body)(nil), "io.casperlabs.casper.consensus.Block.Body")
	proto.RegisterType((*Block_Justification)(nil), "io.casperlabs.casper.consensus.Block.Justification")
	proto.RegisterType((*Block_ProcessedDeploy)(nil), "io.casperlabs.casper.consensus.Block.ProcessedDeploy")
	proto.RegisterType((*Block_GlobalState)(nil), "io.casperlabs.casper.consensus.Block.GlobalState")
	proto.RegisterType((*Bond)(nil), "io.casperlabs.casper.consensus.Bond")
	proto.RegisterType((*GenesisCandidate)(nil), "io.casperlabs.casper.consensus.GenesisCandidate")
	proto.RegisterType((*Era)(nil), "io.casperlabs.casper.consensus.Era")
	proto.RegisterEnum("io.casperlabs.casper.consensus.Block_MessageType", Block_MessageType_name, Block_MessageType_value)
	proto.RegisterEnum("io.casperlabs.casper.consensus.Block_MessageRole", Block_MessageRole_name, Block_MessageRole_value)
}

func init() {
	proto.RegisterFile("io/casperlabs/casper/consensus/consensus.proto", fileDescriptor_consensus_a2847bf026c2e257)
}

var fileDescriptor_consensus_a2847bf026c2e257 = []byte{
	// 1695 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x58, 0x5f, 0x6f, 0x1b, 0xc7,
	0x11, 0xd7, 0x89, 0xff, 0x87, 0x47, 0x89, 0xde, 0x38, 0x2d, 0xc3, 0xd6, 0xb5, 0x42, 0x1b, 0x01,
	0xeb, 0x5a, 0x94, 0xe3, 0x20, 0x05, 0x5a, 0xa0, 0x2e, 0x44, 0x59, 0x16, 0x69, 0xc9, 0x92, 0xb0,
	0x54, 0x62, 0xa0, 0x7d, 0xb8, 0x2e, 0xef, 0xd6, 0xa7, 0x35, 0x8f, 0xb7, 0x97, 0xdb, 0xa5, 0x0a,
	0xbe, 0xb6, 0xdf, 0xa0, 0x28, 0x50, 0xa0, 0x8f, 0xcd, 0x17, 0xe8, 0x7b, 0x0b, 0xe4, 0x5b, 0xf5,
	0xb9, 0xd8, 0xd9, 0xe3, 0x3f, 0x25, 0x8e, 0x68, 0x05, 0xc8, 0x0b, 0xb1, 0xfb, 0x9b, 0x9d, 0xbf,
	0x3b, 0x3b, 0x33, 0x47, 0xe8, 0x08, 0xb9, 0xe7, 0x33, 0x95, 0xf0, 0x34, 0x62, 0x43, 0x95, 0x2d,
	0xf7, 0x7c, 0x19, 0x2b, 0x1e, 0xab, 0x89, 0x5a, 0xac, 0x3a, 0x49, 0x2a, 0xb5, 0x24, 0xbf, 0x10,
	0xb2, 0xb3, 0x38, 0x9f, 0x2d, 0x3b, 0xf3, 0x53, 0xcd, 0x27, 0x37, 0xc8, 0x53, 0x9a, 0x69, 0x6e,
	0x7f, 0xad, 0xc4, 0x56, 0x17, 0x2a, 0x03, 0x11, 0xc6, 0x4c, 0x4f, 0x52, 0x4e, 0x1e, 0x40, 0x4d,
	0x89, 0xd0, 0x63, 0x51, 0x28, 0x53, 0xa1, 0x2f, 0xc7, 0x0d, 0x67, 0xc7, 0x69, 0x57, 0xa8, 0xab,
	0x44, 0xb8, 0x3f, 0xc3, 0x48, 0x1d, 0x72, 0x4a, 0x84, 0x8d, 0xcd, 0x1d, 0xa7, 0xed, 0x52, 0xb3,
	0x6c, 0xfd, 0xd5, 0x81, 0xf2, 0x7e, 0x92, 0xa4, 0xf2, 0x8a, 0x45, 0xa4, 0x03, 0x1f, 0x30, 0x5c,
	0xf3, 0xd4, 0x4b, 0x26, 0xc3, 0x48, 0xf8, 0xde, 0x88, 0x4f, 0x51, 0x92, 0x4b, 0xef, 0xcc, 0x48,
	0xe7, 0x48, 0x39, 0xe6, 0x53, 0x72, 0x04, 0x15, 0x35, 0x33, 0x00, 0x85, 0x56, 0x9f, 0xfe, 0xb2,
	0xf3, 0xfd, 0x6e, 0x76, 0xe6, 0x16, 0xd3, 0x05, 0x6f, 0xeb, 0x1b, 0x17, 0x8a, 0xcf, 0x79, 0x12,
	0xc9, 0x29, 0xb9, 0x0f, 0xd5, 0x00, 0x57, 0xde, 0x25, 0x53, 0x97, 0x99, 0x6e, 0xb0, 0x50, 0x8f,
	0xa9, 0x4b, 0x72, 0x08, 0xc5, 0x4b, 0xce, 0x02, 0x9e, 0x66, 0x1a, 0x77, 0x6f, 0xd2, 0x68, 0x05,
	0x77, 0x7a, 0xc8, 0x44, 0x33, 0x66, 0xf2, 0x7b, 0xc8, 0x0f, 0x65, 0x30, 0x6d, 0xe4, 0x50, 0xc8,
	0xaf, 0xd6, 0x14, 0xd2, 0x95, 0xc1, 0x94, 0x22, 0x23, 0x79, 0x01, 0x15, 0x96, 0x05, 0x4e, 0x35,
	0xf2, 0x3b, 0xb9, 0x76, 0xf5, 0x69, 0xfb, 0x26, 0x29, 0xb3, 0x48, 0xd3, 0x05, 0x6b, 0xf3, 0x7f,
	0x0e, 0x14, 0xad, 0x6d, 0xe4, 0x31, 0x10, 0xe6, 0xfb, 0x72, 0x12, 0xeb, 0x6f, 0x87, 0xbf, 0x9e,
	0x51, 0x16, 0xd1, 0xff, 0x39, 0x54, 0xb4, 0x18, 0x73, 0xa5, 0xd9, 0x38, 0x41, 0x37, 0xf2, 0x74,
	0x01, 0x90, 0x9f, 0x41, 0x25, 0x64, 0xca, 0x4b, 0x52, 0xe1, 0xf3, 0x46, 0x1e, 0xa9, 0xe5, 0x90,
	0xa9, 0x73, 0xb3, 0x37, 0x44, 0xe3, 0x83, 0x0d, 0x71, 0x01, 0xe5, 0x97, 0x0d, 0x80, 0x01, 0xbe,
	0x07, 0xa0, 0x75, 0xe4, 0x8d, 0x45, 0x14, 0x09, 0xd5, 0x28, 0xee, 0x38, 0xed, 0x1a, 0xad, 0x68,
	0x1d, 0xbd, 0x42, 0x80, 0xb4, 0xc0, 0x0d, 0x78, 0xc2, 0xe3, 0x80, 0xc7, 0xbe, 0xe0, 0xaa, 0x51,
	0xda, 0xc9, 0xb5, 0x5d, 0xba, 0x82, 0x19, 0x11, 0xfe, 0x25, 0x13, 0xb1, 0x17, 0xb3, 0x31, 0x6f,
	0x94, 0x31, 0x13, 0x2b, 0x88, 0x9c, 0xb2, 0x31, 0x7f, 0x99, 0x2f, 0x6f, 0xd6, 0x73, 0xcd, 0xbf,
	0x3b, 0x90, 0x37, 0xf1, 0x24, 0x87, 0x50, 0x52, 0x5c, 0x29, 0x21, 0x63, 0xf4, 0x75, 0xfd, 0xdb,
	0x38, 0x90, 0x01, 0xa7, 0x33, 0x5e, 0x23, 0x26, 0x61, 0xd3, 0x31, 0x8f, 0x75, 0x96, 0x19, 0xef,
	0x27, 0x26, 0xe3, 0x6d, 0xfe, 0xdb, 0x81, 0xbc, 0x41, 0xc8, 0x5d, 0xc8, 0xff, 0x99, 0x29, 0xfb,
	0x90, 0xdc, 0xde, 0x06, 0xc5, 0x9d, 0x41, 0x31, 0x6a, 0xb9, 0x19, 0x6a, 0x76, 0x06, 0x45, 0x57,
	0x4d, 0xa0, 0x2b, 0x06, 0x35, 0x3b, 0x83, 0x4e, 0x52, 0xfe, 0xc6, 0x46, 0xd8, 0xa0, 0x66, 0x47,
	0x9e, 0x41, 0x9e, 0xa5, 0xa1, 0x89, 0xac, 0xc9, 0x99, 0x47, 0x6b, 0x1a, 0xb9, 0x9f, 0x86, 0x14,
	0xf9, 0xba, 0x00, 0x65, 0x5f, 0xc6, 0x3a, 0x65, 0xbe, 0xce, 0x22, 0x19, 0x41, 0x6e, 0x3f, 0x0d,
	0x09, 0xc9, 0x8c, 0xb0, 0x2f, 0xdf, 0x9a, 0x70, 0x0c, 0x85, 0x2b, 0x16, 0x4d, 0x78, 0x96, 0xe7,
	0x9f, 0xdf, 0xa4, 0xcd, 0xd6, 0x97, 0x83, 0x93, 0x2f, 0x0d, 0x53, 0x3f, 0x56, 0x9a, 0xc5, 0x3e,
	0xa7, 0x56, 0x46, 0xa6, 0xed, 0x6f, 0x05, 0xa8, 0x9c, 0xf0, 0x90, 0xf9, 0xd3, 0x77, 0x29, 0x3d,
	0x99, 0x29, 0xb5, 0xf7, 0xf0, 0xeb, 0x35, 0x5d, 0x9c, 0x0b, 0xed, 0xa0, 0xf6, 0x4c, 0x6b, 0xf3,
	0x5f, 0x79, 0x28, 0x20, 0x40, 0x3c, 0xd8, 0x92, 0x89, 0x16, 0x32, 0x66, 0x91, 0x67, 0x15, 0x38,
	0x3f, 0x44, 0x41, 0x6f, 0x83, 0xd6, 0x66, 0xf2, 0xac, 0x82, 0x8f, 0xa1, 0x3a, 0x9c, 0x6a, 0xae,
	0xbc, 0x85, 0xf9, 0xe6, 0xde, 0x00, 0x41, 0x7b, 0xe4, 0x1e, 0x54, 0x44, 0xac, 0xbd, 0x45, 0x50,
	0x0b, 0xbd, 0x0d, 0x5a, 0x16, 0xb1, 0xb6, 0xe4, 0x97, 0x60, 0xd6, 0x5e, 0x24, 0x94, 0xc6, 0x64,
	0x58, 0xa3, 0x3e, 0xd9, 0x90, 0xf7, 0x63, 0x7d, 0x22, 0x94, 0xee, 0x6d, 0xd0, 0x92, 0xb0, 0x4b,
	0xf2, 0x00, 0x5c, 0xa5, 0x53, 0x11, 0x87, 0x99, 0xb6, 0x42, 0x96, 0x5c, 0x55, 0x8b, 0x5a, 0x85,
	0x03, 0xc8, 0xb6, 0x56, 0x67, 0x11, 0x75, 0x3e, 0x59, 0x4f, 0xe7, 0x00, 0x19, 0x33, 0xb5, 0xa0,
	0xe6, 0x3b, 0x72, 0x1f, 0x20, 0x92, 0x73, 0xbd, 0xa5, 0x1d, 0xa7, 0x9d, 0xeb, 0x6d, 0xd0, 0x8a,
	0xc1, 0xac, 0xd6, 0x23, 0x28, 0x0d, 0x45, 0xe8, 0x89, 0x58, 0xe3, 0xeb, 0xae, 0x3e, 0x7d, 0xbc,
	0x9e, 0xc6, 0xae, 0x08, 0xfb, 0xb1, 0xd1, 0x56, 0x1c, 0xe2, 0x8a, 0xfc, 0x0e, 0x72, 0xa6, 0xc6,
	0x55, 0xd6, 0x6b, 0x1e, 0x56, 0xc8, 0x31, 0x9f, 0xf6, 0x36, 0xa8, 0xe1, 0xeb, 0x96, 0xb2, 0x4c,
	0x6b, 0x7d, 0xe3, 0x40, 0xcd, 0xde, 0xf2, 0x60, 0x32, 0x1e, 0xb3, 0xf4, 0xc7, 0x6b, 0x24, 0x2b,
	0x7d, 0x20, 0x77, 0xeb, 0x3e, 0xd0, 0xfa, 0xaf, 0x03, 0x6e, 0x37, 0x92, 0xfe, 0x68, 0xe6, 0xc0,
	0x3d, 0x80, 0xa1, 0xd9, 0x2f, 0xdb, 0x5f, 0x41, 0x04, 0xcd, 0x7f, 0x7e, 0xcd, 0xfc, 0x1b, 0x6f,
	0x00, 0x85, 0x5f, 0xb7, 0x7e, 0xa5, 0x85, 0xe7, 0x7e, 0x40, 0x0b, 0xff, 0x7a, 0x0b, 0x0a, 0xa8,
	0xe1, 0xc7, 0xb1, 0xfb, 0xd9, 0x4a, 0xfb, 0x7e, 0xb4, 0x9e, 0x8c, 0xa5, 0xee, 0xbd, 0xe2, 0x77,
	0xfe, 0xf6, 0x7e, 0x37, 0xff, 0x59, 0x9a, 0xb7, 0xef, 0x07, 0x50, 0x4b, 0x58, 0xca, 0x63, 0x8d,
	0x9e, 0x73, 0xd5, 0x70, 0x6c, 0x6b, 0xb4, 0x60, 0x0f, 0x31, 0xf2, 0x47, 0xd8, 0x7a, 0x3b, 0x51,
	0x5a, 0xbc, 0x11, 0x3e, 0x33, 0xa5, 0x47, 0x35, 0x36, 0x31, 0x67, 0x3e, 0x5b, 0xcf, 0x85, 0x97,
	0xcb, 0xbc, 0xf4, 0x9a, 0x28, 0x72, 0x04, 0x05, 0x7c, 0x22, 0x59, 0x58, 0x3e, 0x5d, 0x4f, 0xe6,
	0x51, 0x24, 0x87, 0x2c, 0x1a, 0x18, 0x46, 0x6a, 0xf9, 0x57, 0x07, 0x84, 0xfc, 0xb5, 0x01, 0x61,
	0x65, 0xf0, 0x28, 0x5c, 0x1f, 0x3c, 0xfe, 0x04, 0x75, 0x1c, 0x4f, 0x7d, 0x19, 0x79, 0x57, 0x3c,
	0xc5, 0xb6, 0x5e, 0x7b, 0x9f, 0xe6, 0x73, 0x9e, 0x71, 0x7f, 0x69, 0x99, 0xe9, 0x76, 0xb2, 0x0a,
	0x90, 0x8f, 0x71, 0x02, 0x31, 0x2f, 0x1b, 0x27, 0x22, 0xac, 0x4f, 0x35, 0x9a, 0xbd, 0xf6, 0x03,
	0x03, 0xdd, 0x30, 0x80, 0x90, 0xcf, 0xe1, 0xa7, 0x57, 0x2c, 0x12, 0x01, 0xd3, 0x32, 0xf5, 0x6c,
	0xb2, 0x2a, 0xfe, 0x95, 0x17, 0x4f, 0xc6, 0x58, 0x89, 0x6a, 0xf4, 0xee, 0x9c, 0x6c, 0x9f, 0x24,
	0xff, 0xea, 0x74, 0x32, 0x26, 0x4f, 0x60, 0x81, 0x2f, 0x4f, 0x68, 0x80, 0x01, 0x22, 0x73, 0xda,
	0x62, 0x46, 0xfb, 0x0d, 0x7c, 0xb4, 0xc4, 0x91, 0xf2, 0x2b, 0x6f, 0xe9, 0x69, 0x6c, 0x21, 0xdb,
	0x4f, 0x16, 0x6c, 0x29, 0xbf, 0xea, 0xce, 0xdf, 0xc9, 0x87, 0x50, 0x7c, 0xeb, 0xa5, 0x2c, 0x1e,
	0x35, 0xaa, 0x18, 0xe2, 0xc2, 0x5b, 0xca, 0xe2, 0x11, 0xb9, 0x00, 0x77, 0xcc, 0x95, 0x62, 0x21,
	0xf7, 0xf4, 0x34, 0xe1, 0x0d, 0x77, 0xc7, 0x69, 0x6f, 0xad, 0x7b, 0xd3, 0xaf, 0x2c, 0xe7, 0xc5,
	0x34, 0xe1, 0xb4, 0x3a, 0x5e, 0x6c, 0x96, 0xa5, 0xa6, 0x32, 0xe2, 0x8d, 0x0f, 0x6e, 0x21, 0x95,
	0xca, 0x68, 0x21, 0xd5, 0x6c, 0xc8, 0x43, 0xd8, 0x1a, 0xf1, 0xe9, 0xb2, 0xcb, 0xdb, 0xe8, 0xb2,
	0x6b, 0x4a, 0xf7, 0xdc, 0xd1, 0x8f, 0xa0, 0x9c, 0xca, 0x49, 0x1c, 0x78, 0x22, 0x68, 0xd4, 0xd1,
	0xd5, 0x12, 0xee, 0xfb, 0x81, 0x49, 0xc3, 0x31, 0x0b, 0x85, 0xef, 0x0d, 0x85, 0x6e, 0xdc, 0xd9,
	0x71, 0xda, 0x65, 0x5a, 0x46, 0xa0, 0x2b, 0xb4, 0x25, 0x8a, 0xd8, 0xc6, 0x88, 0xd8, 0x09, 0xd7,
	0x00, 0x26, 0x4c, 0x2f, 0xf3, 0xe5, 0x62, 0xbd, 0xd4, 0x7c, 0x9d, 0x4d, 0x98, 0x67, 0x50, 0xb2,
	0xd9, 0x61, 0xdf, 0xe4, 0x1a, 0xa9, 0x68, 0x3d, 0x3b, 0x4f, 0xa5, 0xcf, 0x95, 0xe2, 0x81, 0x2d,
	0xfd, 0x74, 0x26, 0xa5, 0x39, 0x86, 0xda, 0xca, 0x4b, 0x7c, 0x67, 0x6a, 0x38, 0xef, 0x4c, 0x8d,
	0x47, 0x70, 0x27, 0x62, 0x9a, 0x2b, 0xbd, 0x1c, 0x1f, 0xfb, 0x65, 0xb6, 0x6d, 0x09, 0xf3, 0x10,
	0x35, 0xff, 0xe3, 0xc0, 0xf6, 0x35, 0x5b, 0xc8, 0x33, 0x28, 0x5a, 0x6b, 0xb2, 0x21, 0xe8, 0x93,
	0xf5, 0xda, 0x17, 0xcd, 0xb8, 0xcc, 0xe0, 0xe6, 0x4b, 0x65, 0x67, 0xe5, 0x3c, 0xc5, 0xb5, 0xb9,
	0x0a, 0xa1, 0x3c, 0x9e, 0xa6, 0x32, 0xc5, 0x12, 0x52, 0xa6, 0x25, 0xa1, 0x0e, 0xcd, 0xd6, 0x14,
	0x37, 0xc4, 0xbd, 0xec, 0x82, 0xed, 0xa8, 0x4b, 0x5d, 0x04, 0xb3, 0x0c, 0x20, 0x77, 0xb1, 0xfe,
	0x84, 0x76, 0x54, 0xa9, 0x51, 0xbb, 0x69, 0xfe, 0xc3, 0x81, 0xea, 0x52, 0x8d, 0x31, 0x69, 0x91,
	0xa4, 0xdc, 0xc3, 0xd7, 0xbe, 0xdc, 0x24, 0xdc, 0x24, 0xe5, 0x78, 0x02, 0xd3, 0xe2, 0x13, 0xd8,
	0x4e, 0xa4, 0xd2, 0xcb, 0xc7, 0x6c, 0x74, 0x6a, 0x06, 0x5e, 0x9c, 0xfb, 0x2d, 0x14, 0x86, 0x32,
	0x0e, 0x66, 0xbd, 0xf7, 0xe1, 0x8d, 0x37, 0x2b, 0xe3, 0x80, 0x5a, 0x96, 0xd6, 0x43, 0xa8, 0x2e,
	0x3d, 0x09, 0x52, 0x81, 0x42, 0xf7, 0xe4, 0xec, 0xe0, 0xb8, 0xbe, 0x41, 0x00, 0x8a, 0xdd, 0xfd,
	0x93, 0x93, 0xb3, 0x8b, 0xba, 0xd3, 0xea, 0xcf, 0x4f, 0x61, 0x56, 0xd7, 0xa0, 0xf2, 0xc5, 0xe9,
	0xf3, 0xc3, 0x17, 0xfd, 0xd3, 0xc3, 0xe7, 0xf5, 0x0d, 0xe2, 0x42, 0xf9, 0x9c, 0x9e, 0x9d, 0x9f,
	0x0d, 0xf6, 0x4f, 0xea, 0x0e, 0xa9, 0x83, 0x7b, 0x70, 0x76, 0xfa, 0xa2, 0x4f, 0x5f, 0xed, 0x5f,
	0xf4, 0xcf, 0x4e, 0xeb, 0x9b, 0xa4, 0x0a, 0xa5, 0xd7, 0xfd, 0x8b, 0xd3, 0xc3, 0xc1, 0xa0, 0x9e,
	0x6b, 0xfd, 0x05, 0xbf, 0x79, 0xe2, 0xe0, 0x16, 0xf9, 0xd2, 0xc5, 0xd8, 0x8e, 0x66, 0xb5, 0xfd,
	0xbd, 0x06, 0x2e, 0x6a, 0x59, 0xed, 0x00, 0xdf, 0x9a, 0x42, 0xfd, 0x88, 0xc7, 0x5c, 0x09, 0x75,
	0xc0, 0xe2, 0xc0, 0xe8, 0xe1, 0x37, 0x35, 0xed, 0x95, 0x21, 0x67, 0xf3, 0xf6, 0x43, 0xce, 0xd7,
	0x9b, 0x90, 0x3b, 0x4c, 0xd9, 0x77, 0x54, 0x06, 0xe7, 0x3b, 0x2a, 0xc3, 0xa7, 0xf0, 0x61, 0xd6,
	0x50, 0xaf, 0x1d, 0xb6, 0x89, 0x40, 0x2c, 0xf1, 0x78, 0x99, 0xe5, 0x1e, 0x80, 0xd2, 0x2c, 0xd5,
	0x9e, 0x16, 0xfe, 0x68, 0xf6, 0x55, 0x8c, 0xc8, 0x85, 0xf0, 0x47, 0x26, 0xc1, 0x79, 0x1c, 0x58,
	0xa2, 0xfd, 0x28, 0x2e, 0xf1, 0x38, 0x40, 0xd2, 0x63, 0x20, 0x43, 0x29, 0x47, 0x66, 0x92, 0x5e,
	0xd2, 0x64, 0x3f, 0x8e, 0xeb, 0x19, 0x65, 0xa1, 0xe7, 0x3e, 0x54, 0x23, 0xec, 0xfa, 0x9e, 0xe2,
	0x3c, 0xc0, 0xb1, 0xdb, 0xa5, 0x60, 0xa1, 0x01, 0xe7, 0xc1, 0x22, 0x2d, 0x4b, 0xef, 0x9d, 0x96,
	0xdd, 0xd7, 0x7f, 0xf8, 0x22, 0x14, 0xfa, 0x72, 0x32, 0xec, 0xf8, 0x72, 0xbc, 0x77, 0x19, 0x30,
	0x7f, 0x77, 0xe5, 0xcf, 0xa1, 0x5d, 0xce, 0x77, 0xc3, 0x34, 0xf1, 0x77, 0x43, 0xb9, 0x3b, 0xd1,
	0x22, 0xda, 0xc3, 0x0e, 0x39, 0x9c, 0xbc, 0xd9, 0xfb, 0xfe, 0xff, 0x90, 0x86, 0x45, 0x3c, 0xf8,
	0xd9, 0xff, 0x03, 0x00, 0x00, 0xff, 0xff, 0x44, 0x8a, 0x54, 0x9c, 0xbc, 0x12, 0x00, 0x00,
}
